### ISSUE TITLE
Unused strings not removed

### ISSUE THREAD

**Issue by samizzo** [open-watcom/open-watcom-v2#1027]
I have this situation:

In log.h:
```
#if defined(BUILD_DEBUG)
void log_debug(const char* fmt, ...);
#else
inline void log_debug(const char* fmt, ...) { }
#endif
```

Then in some other .c file:
```
void SomeFunc()
{
    log_debug("message goes here\n");
}
```

when I do a final build with optimisations turned on, the log strings are still visible in the executable. I would have expected that since they're no longer referenced they could have been stripped out. Am I missing a compiler or linker flag for this or does it not currently do this?

Thanks,
Sam

**Comment by jmalak** [comment]
Are you sure that your string is unreferenced?

**Comment by samizzo** [comment]
Yeah, it's definitely unreferenced by any other code. It's just a string literal that's passed into that `log_debug` function. This is my debug log system which is disabled in release builds. Indeed if I step through the code there's no `log_debug` call but I do see it pushing the string onto the stack, which seems weird:
![image](https://user-images.githubusercontent.com/1753040/213055135-5a02ace4-a28b-4c09-94cc-33d95bc04649.png)

**Comment by jmalak** [comment]
Sorry, your literal string is referenced because function exists even if blank body.
You relate to assumption that if function is optimize out then literal string is unreferenced, but it is not true.
We can talk about optimizer that didn't remove your literal string, but it is another story.
By C language standard it is referenced. if you want to unreference any literal string then you must use some macro which doesn't reference it in case you don't want generate any reference, otherwise you relate to optimizer capabilities and it is undefined behaviour (by C standard).
Try to compile without optimizing code ( -od option ).

The code could looks like

for pre C99 code

```
#if defined(BUILD_DEBUG)
void log_debug(const char* fmt, ...);
#define LOG_DEBUG(x)  log_debug x
#else
#define LOG_DEBUG(x)
#endif

then call to debug logging is as, you must use arguments in brackets because it doesn't have variadic macro
LOG_DEBUG((".....", ".....", ....));
```
or for C99 code, which have variadic macro

```
#if defined(BUILD_DEBUG)
void log_debug(const char* fmt, ...);
#define LOG_DEBUG(...)  log_debug(__VA_ARGS__)
#else
#define LOG_DEBUG(...)
#endif

then call to debug logging is as standard variadic function
LOG_DEBUG( ".....", ".....", .... );
```

These constructs ensure that literal strings are not referenced and disapear from generated code.

**Comment by samizzo** [comment]
Thanks for the explanation! I didn't realise that. I assumed that because the function was optimised out (due to being inline and empty) that the optimiser would also remove the string. It seems strange to me that the compiler it still pushes the string address onto the stack but never makes use of that value.

Thanks for the alternative solutions too. I actually didn't realise the compiler supported C99 - I have wanted to use variadic macros for ages!

**Comment by jmalak** [comment]
Use of macros is portable way (C standard) that you can compile it with other compilers with same behavior.
Anyway OW is by default in C89/90 mode you need to use -za99 for C99 mode (not fully implemented).
OW optimizer could be improve to do such optimization for your case, but it is not general solution of this issue with referenced/unreferenced string literals, it is realy optimization which can happen or not happen.

**Comment by groessler** [comment]
> Thanks for the explanation! I didn't realise that. I assumed that because the function was optimised out (due to being inline and empty) that the optimiser would also remove the string. It seems strange to me that the compiler still pushes the string address onto the stack but never makes use of that value.

The function is not optimized out because it's not "static" and could be called from another object file. The compiler is required to provide a non-inlined version of this function in this case.

But @jmalak's solution is a better way than depending on the optimizer and the way how it's normally done.
