### ISSUE TITLE
Cannot directly pass parameters in AH to externally defined function with #pragma aux

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#1030]
I have a 16-bit program calling into an externally defined function that takes AH as a parameter. I am able to pass other parameters through 16-bit registers, but any 8-bit registers are pushed on the stack. Consider this example:

print_x86.asm
```nasm
SEGMENT .code USE16 CLASS=CODE

GLOBAL DOS_func_
DOS_func_:
  int 0x21
  ret
```

print.c
```C
#pragma aux DOS_func parm [ dx ] [ ah ]
void DOS_func(const char *str, unsigned char func);

const char *STR = "Hello, World$";

#pragma aux main modify [ ax bx cx dx si di ]
void main() {
  DOS_func(STR, 0x9);
}
```

When I build this and disassemble I get:
```
$ wcc -s print.c
print.c: 10 lines, 0 warnings, 0 errors
Code size: 11

$ wdis print.o
Module: print.c
GROUP: 'DGROUP' CONST,CONST2,_DATA

Segment: _TEXT BYTE USE16 0000000B bytes
0000				main_:
0000  B8 09 00				mov		ax,0x0009
0003  50				push		ax
0004  BA 00 00				mov		dx,offset DGROUP:L$1
0007  E8 00 00				call		DOS_func_
000A  C3				ret

Routine Size: 11 bytes,    Routine Base: _TEXT + 0000

No disassembly errors

Segment: CONST WORD USE16 0000000E bytes
0000				L$1:
0000  48 65 6C 6C 6F 2C 20 57 6F 72 6C 64 24 00       Hello, World$.
```

This incorrectly passes the `func` parameter on the stack instead of in the `AH` register (which will crash the program).

I can work around this bug by defining a proxy function in the C code as follows:

print2.c
```C
#pragma aux DOS_func parm [ dx ] [ ah ]
void DOS_func(const char *str, unsigned char func);

#pragma aux DOS_func2 parm [ dx ] [ ah ] = "call DOS_func"
static void DOS_func2(const char *str, unsigned char func);

#define STR "Hello, World$"

#pragma aux main modify [ ax bx cx dx si di ]
void main() {
  DOS_func2(STR, 0x9);
}
```

Building and disassembling:
```
$ wcc -s print2.c
print.c: 13 lines, 0 warnings, 0 errors
Code size: 9

$ wdis print2.o
Module: print2.c
GROUP: 'DGROUP' CONST,CONST2,_DATA

Segment: _TEXT BYTE USE16 00000009 bytes
0000				main_:
0000  B4 09				mov		ah,0x09
0002  BA 00 00				mov		dx,offset DGROUP:L$1
0005  E8 00 00				call		DOS_func_
0008  C3				ret

Routine Size: 9 bytes,    Routine Base: _TEXT + 0000

No disassembly errors

Segment: CONST WORD USE16 0000000E bytes
0000				L$1:
0000  48 65 6C 6C 6F 2C 20 57 6F 72 6C 64 24 00       Hello, World$.
```

Doing this is cumbersome when I have a lot of functions to define. I am not sure why the first version is generating the incorrect x86 assembly.

**Comment by jmalak** [comment]
It is interface which describe C external function not inline assembly function.
Therefore you need take into account how registers are allocated for C function that you can not assign registers as you want.
There are restrictions and if you don't aply them code generator put such parameters on the stack, the same if not enough registers available then parameters are put on the stack.
Please read following section from OW documentation which describe how registers are allocated or C function.
https://open-watcom.github.io/open-watcom-v2-wikidocs/cguide.html#16Mbit__Passing_Arguments_Using_RegisterMBased_Calling_Conventions

Registers are allocated from register set [AX BX CX DX] in following order AX DX BX CX
but if you need far pointer or long argument then it can be only DX:AX or CX:BX no other combination
in your case first parameter is in AX second in DX, but you cannot select AH
because there is rule char parameter is extend to int and passed by AX

**Comment by jmalak** [comment]
As soon as you will use AX register instead of AH then all will be as you expected.
You cannot use higher byte registers for passing parameters, as soon as you use it in #pragma aux then all parameters from this position will be put on the stack.
