### ISSUE TITLE
#pragma aux cannot return far pointers with value [ es bp ] but supports near pointers in value [ bp ]

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#1033]
The VGA fonts can be retrieved with interrupt 10h, sub function AX = 1130h. However, they are returned as a far pointer in ES:BP which is an invalid return register to WATCOM. Consider the example program:

font.c
```C
unsigned char far *VGA_get_font();
#pragma aux VGA_get_font value [ es bp ] = \
  "mov ax, 0x1130" \
  "mov bh, 0x3" \
  "int 0x10" \
  modify [ ax bh ]

void main() {
  unsigned char far *font;
  font = VGA_get_font();
}
```

Compiling this gives the following error:

```
$ wcc -s font.c
font.c: 12 lines, 0 warnings, 0 errors
font.c(12): Error! E1121: Procedure 'VGA_get_font' has invalid return register in #pragma
Code size: 12
```

Changing `bp` in `[ es bp ]` to any of `ax`, `bx`, `cx`, `dx`, `si` or `di` works fine.

However, defining an inline assembly function that returns a near pointer using `value [ bp ]` is allowed. Consider this example:

null.c
```C
#pragma aux get_null = "xor bp, bp" value [ bp ]
int *get_null();

int *main() {
  return get_null();
}
```

Building and disassembling gives:

```
$ wcc -s null.c
null.c: 7 lines, 0 warnings, 0 errors
Code size: 5

$ wdis null.o
Segment: _TEXT BYTE USE16 00000005 bytes
0000				main_:
0000  33 ED				xor		bp,bp
0002  89 E8				mov		ax,bp
0004  C3				ret

Routine Size: 5 bytes,    Routine Base: _TEXT + 0000

No disassembly errors
```

If near pointers can use the `BP` register, I don't understand why `BP` is invalid for far pointers.

**Comment by rdos314** [comment]
You will need to create an address (in assembly) that doesn't involve bp (and save bp). You cannot return an address in es:bp to C.

**Comment by negge** [comment]
> You will need to create an address (in assembly) that doesn't involve bp (and save bp). You cannot return an address in es:bp to C.

Right, I see the error. My question is why this is not allowed if BP is a valid register for near pointers.

**Comment by jmalak** [comment]
I am sorry, but I need to [point you to OW documentation](https://open-watcom.github.io/open-watcom-v2-wikidocs/cguide.html#16Mbit__Passing_Arguments_in_Registers).
these use is not for current users and therefore it is not check much and don't report any issue even if you do mistake.
Usage of #pragma aux is for experienced programmer which know what to do.
Please check what is possible and if it can be use and doesn't work as expected then raise issue.

In documentation is explaned that [es bp] is not valid register combination therefore it doesn't work as you expected.
Anyway [e]bp or [e]sp registers are privileged that can be use only if it is not allocated by Code generator.
[e]bp register is used for C function as frame pointer that it can be used only for function which don't have parameters and auto variable otherwise it is used by Code generator. CG has highest priority for register allocation that ignore what is in #pragma aux if it is incorrect use.
If you want to use [e]bp then it is your responsibility in inline function to save it and restore on return but use for parameter passing is limited.

**Comment by jmalak** [comment]
Anyway you think that BP register is alowed for near pointer.
It is not true, this allocation is simply ignored by CG and your code overwrite BP and you will have a problems.

Try to look on in-line code in bld/watcom/h/int10.h which is for handling Video interrupt in OW code base.
