### ISSUE TITLE
too many bugs

### ISSUE THREAD

**Issue by gfernval** [open-watcom/open-watcom-v2#1041]
Excuse my ignorance, I see there are corrections in the source code almost every day, does this means that when Watcom C was opensourced the source code was full of bugs?
For example, the last correction was:

"correct mistake in import symbol record numberring"

-   sym = (coff_sym_section *)( c_file->symbols + c_file->header.num_symbols );
+   sym = (coff_sym_section *)( c_file->symbols + c_file->header.num_symbols++ );

This bug was present in OpenWatcom 11?

**Comment by jmalak** [comment]
This code is OK, because old code increment it later but new one not.
sym pointer point to same address, this change is only for code transparency.
It is part of syncing code in ORL and NWLIB projects which do the same thing for PE/COFF import libraries records.
It is part of MIPS and X64 platform implementation/review.
