### ISSUE TITLE
OW fails to build at idedemo/src/*/box.obj

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1060]
OW build still fails here. 
Tested owtools: clang (v15), gcc (v12) and i tried also gcc-10.

I tried BUILDER_OPT="-v "  OWVERBOSE="1"

Failure is always  for bld/idedemo/src/*/box.obj
for all targets: os2, win, win32 and win386.
(all targets only visible, when adding "-i" to BUILDER_OPT)

Message examples for target os2:
wmake -i -h -f temp.mk1 tree_depth=4   "/full_path_here/bld/idedemo/src/os2/box.obj"

Warning(39): Target (/full_path_here/bld/idedemo/src/os2/box.obj) not mentioned in any makefile
Error(F38): (/full_path_here/bld/idedemo/src/os2/box.obj) does not exist and cannot be made from existing files
Error(E02): Make execution terminated

Any idea, how to fix that?

When i add "-i"  to BUILDER_OPT,
or when i comment out 'idedemo' in 'bld/builder.ctl',
then the build runs to the end.

wmake file for os2
[temp.mk1.gz](https://github.com/open-watcom/open-watcom-v2/files/11009212/temp.mk1.gz)
[drawos2.mk1.gz](https://github.com/open-watcom/open-watcom-v2/files/11009214/drawos2.mk1.gz)

wmake file for win32
[temp.mk1.gz](https://github.com/open-watcom/open-watcom-v2/files/11009221/temp.mk1.gz)
[draw32.mk1.gz](https://github.com/open-watcom/open-watcom-v2/files/11009224/draw32.mk1.gz)

-- 
Regards ... Detlef

**Comment by winspool** [comment]
bide2mak -l -r drawos2.tgt -i ../../../../bld/ide/cfg/os2386/
sed -f "../../../../bld/idedemo/convtool.sed" -f "../../../../bld/idedemo/convos2.sed" drawos2.mk1 >temp.mk1
wmake -i -h -f temp.mk1 tree_depth=4 "/_s/ow/github/bld/idedemo/src/os2/box.obj"
Warning(W39): Target (/_s/ow/github/bld/idedemo/src/os2/box.obj) not mentioned in any makefile
Error(F38): (/_s/ow/github/bld/idedemo/src/os2/box.obj) does not exist and cannot be made from existing files
Error(E02): Make execution terminated
Error(E42): Last command making (/_s/ow/github/bld/idedemo/src/os2/box.obj) returned a bad status
Error(E02): Make execution terminated

**Comment by winspool** [comment]
bld/idedemo/src/os2$ which wmake
/_s/ow/github/build/binbuild/wmake

**Comment by winspool** [comment]
Only the parts related to OpenWatcom posted here.
/_v/ow is a link to the unpacked OpenWatcom CI build from ~24h ago (/_v/ow_ci)
/_s/ow/github is the current OpenWatcom source tree from github


$ env | sort | grep ow

DOS_INCLUDE=/_v/ow/h/dos:/_v/ow/h
LIBLINUX=/_v/ow/lib386/linux:/_v/ow/lib386
LINUX_INCLUDE=/_v/ow/lh:/_v/ow/h
NT_INCLUDE=/_v/ow/h/nt:/_v/ow/h
OS2_INCLUDE=/_v/ow/h/os2:/_v/ow/h

PATH=/_s/ow/github/build/binbuild:/_s/ow/github/build:...removed...:/_v/ow/binl64:/_v/ow/binl:...removed...:

QNX_INCLUDE=/_v/ow/h
WATCOM=/_v/ow
WINDOWS_INCLUDE=/_v/ow/h/win:/_v/ow/h


Hope, that helps.

**Comment by jmalak** [comment]
Sorry, why you give me what you want and not what I need?
It is hard to help you, because I get only the same info as before, but not something what can help me with analysis.

I thing it is clean what happen.
You have OW custom setup even if you use non-Watcom toolchain
It clash with internal OW toolchain setup handled by OW build system.
Don't setup OW for OW build system if you use non-Watcom toolchain.

**Comment by jmalak** [comment]
I created a fix for ide2demo project which could help you, but the problem is that you use "custom" OW run-time configuration even if you don't use Watcom toolchain for OW build that it clash with OW build system internal configuration.
Such configuration is not supported for OW build system.
If you use OW to build OW then only standard host configuration is supported otherwise you must change your configuration to be standard, by example by initialization script.
It means remove any "custom" change and configure it for only for host system or remove it if you are building by non-Watcom toolchain.

**Comment by jmalak** [comment]
no response, closed
