### ISSUE TITLE
W1058: implib option not valid for a DOS executable; Error! E3033: directive error near 'implib'

### ISSUE THREAD

**Issue by SamuelMarks** [open-watcom/open-watcom-v2#1090]
Found on this repo
https://github.com/SamuelMarks/cmocka/tree/msvc2005

```cmd
cmake -DCMAKE_BUILD_TYPE="Debug" -G "Watcom WMake" -DCMAKE_SYSTEM_NAME="DOS" -DCMAKE_SYSTEM_PROCESSOR="I86" ..
cmake --build .
```

I'm trying to add support for OpenWatcom's DOS target to cmocka :)

**Comment by jmalak** [comment]
It is not OW issue.
It is CMake project configuration. 
It looks like that it is configured for Windows DLL use.
It is wrong for DOS.
You need review CMake project configuration and correct it for DOS target.

**Comment by SamuelMarks** [comment]
Happy to do such configuration. Is there an example I'm meant to be following?

I was able to get DOS target builds working for another project of mine https://github.com/offscale/c89stringutils/releases/tag/0.0.2 - with basically no changes required to the CMakeLists.txt: https://github.com/offscale/c89stringutils/blob/master/CMakeLists.txt

**Comment by jmalak** [comment]
I am sorry, but I don't use CMake.
But because it is created for Microsoft Visual Studion (only Windows target) then it can imply to use DLL by default.
You need somehow define if you use DOS target with Watcom then it uses static libraries instead of DLL.
Then you can get errors that these static libraries doesn't exists and you will need to configure to create them first instead of import library which is derived from DLL.
It requires some knowledge about CMake files.
