### ISSUE TITLE
ESET false positive

### ISSUE THREAD

**Issue by Count-MHM** [open-watcom/open-watcom-v2#1093]
ESET falsely identifies Open Watcom installer as a Trojan?

![2023-05-23 14_22_26-](https://github.com/open-watcom/open-watcom-v2/assets/71083058/f3cfb684-2281-4fbd-add8-88b022605fc6)

**Comment by jmalak** [comment]
I am not responsible for such software which report some virus infection.
There is minimum probability for such infection, because OW build system uses prepared image (by GitHub) and we doesn't load any software for build process, except DOSBOX. All other software is build from sources or are in git repository (what is used for documentation build only) as static image for very long time.
