### ISSUE TITLE
glibc:  A static linked program should not use dlopen

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1133]
I just recognized from my build log,
that the static linked application "wv"
has a runtime dependency to the shared glibc libraries
with the same glibc version used for linking "wv".

/usr/bin/ld: dipld.obj: in function `DIPSysLoad':
/xxxxxxxxx/bld/wv/linux/linuxx64/../../../../bld/dig/c/linux/dipld_so.c:63: Warnung: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking.

This is usually avoided by importing all possible libraries/modules 
into the main program.

**Comment by jmalak** [comment]
Do you thing it is wrong, how?

**Comment by winspool** [comment]
> Do you thing it is wrong, how?

Welcome to the DLL hell with the glibc versioned exports

* Your process has two concurrent libc running in the same process
* when the shared glibc version on the user machine is different from the glibc linked to the program, everything can fail
* It crashed nearly all the time.


Example:
https://stackoverflow.com/questions/57476533/why-is-statically-linking-glibc-discouraged


Example from current ci build:
```
detlef@i7 [/_v/ow_ci]
$ binl64/wd 
Speicherzugriffsfehler (Speicherabzug geschrieben)
detlef@i7 [/_v/ow_ci]
$ binl/wd 
�*��
```

Yes,  the failure message from binl/wd is broken.

My previous unpacked ci-build was from 4.9
and the failure from bin/wd was, that std.trp could not be loaded.

So on linux, debugging does not work at all.

**Comment by jmalak** [comment]
Sorry don't copy some info which is unrelated to use of dynamic loading for these piece of OW code.
You should first study code and think why it is used this way.
Take into account that WATCOM and Open Watcom developers are clever people and know what and why do things this way.

- our use of dynamic modules loading has nothing to do with static/dynamic linking
- GCC is generating lot of various warning, but it doesn't mean that code is wrong
- in our case we use dynamic module loading for reconfigurable modules in debuger which are loaded/unloaded on run-time
- it is related to MAD, DIP and TRAP modules which are loaded by debugger
- normaly it is released by DLL/shared libraries, but OW doesn't support shared libraries therefore on platforms as Linux or QNX use own loaders for such modules and on *NIX platforms this loader uses dlload etc. functions but only to load executable image to memory. Next OW loader do code relocation because used executable format is REX (Pharlap) etc.

**Comment by winspool** [comment]
Sorry, binl64/wd is always crashing here
and I assumed, that this is the result 
of the combination of
static linking of glibc and the use of dlopen,
as the warning suggested.

I mark this as WONTFIX and already opened
a new bug report about wd not working on linux

**Comment by jmalak** [comment]
64-bit version is different story.
We have no implemented 64-bit executable debuging, only 32-bit

On 64-bit you can only use remote debugging with TCP connection (for 32-bit executable).
first you need start server by tcpserv command where you want run executable.
next start wd -trap=tcp;<remote ip adress or blank for local>
