### ISSUE TITLE
Needed:  Umbrella LISTSERV-type email list covering all news for all forks of OW

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#116]
I am deeply interested in monitoring, encouraging, and facilitating OW development and deployment.  There is currently AFAIK no efficient way to do any of this.  In particular, the "official" OW web site does great harm because it is where 99% of new searchers land, and it proclaims that OW is dead.

(This is the message between the lines.  The Official OW web site says that (1) it is the official web site, that (2) an active community of developers and users can be found there, and (3) new releases are uploaded regularly.  But within 45 seconds of reading that happy news, the new visitor discovers that (A) it is a ghost town, and (B) the latest release was uploaded years ago.  Two plus two equals: OW is dead.)

An inflow of hopeful potential users and developers is critically important.  Such people must not be obstructed from encountering those who have already found each other and are enthusiastically working together and helping each other use the latest OR greatest OW.

The official OW web site, by choking off this inflow of new people, is the greatest friend of those organizations that would like to see OW go away because it is a competitive threat.

IMO, two things need to be done, and done quickly:  First, the OW community needs a newspaper / newsletter / email server so that interested persons can find the community, make contact with people in it, see what active forks exist, and easily get involved.  Second, the OW community needs to ask that the "official" web site needs to either be taken down or updated so that people who visit there don't get the "OW is dead" message.

WDYT?

**Comment by revelator** [comment]
A forum site like the one darkmod uses with links to the github pages seem to work just fine :) but thats 
just one option, there might be many more. For on expand the github page with a wiki detailing build instructions, pitfalls with different compilers (like the intel compiler i use), tips and tricks to use open watcom as your prefered compiler etc. Im also drumming for more developers to chime in on several sites. Quite a lot of game devs still use it for retro games like quake, building real dos versions or winquake versions with it, and they know a thing or two about compilers also.

**Comment by pchapin** [comment]
Adding material to the Wiki on GitHub sounds like a good idea.

Of course there are the Open Watcom newsgroups. They have been around for years and are still active. Some discussion about this fork has taken place there. Perhaps they can serve the role of being a central location for the entire Open Watcom community.

**Comment by revelator** [comment]
Also good, Somewhere to discuss changes in realtime might be a good idea also so dont count out forums ;) they served the community i came from quite well over the years and the oldest of devs are still active on them (some 20 years plus like myself).

I know from experience that most devs involved in building compilers would want to keep a tight lid on who can apply because of lack of knowledge or overestimation of there own abilities on some who might chime in, so in the community i come from we keep the development off limits but otherwise open to the public. One can then ask for developer access, and if he or she knows there thing that could be granted, meanwhile everyone gets to know each other and are free to exchange ideas (sometimes even interresting code) on the forums. This sometimes happens to also give the head devs some ahaaa moments (hey blind monkey sometimes also finds bananas, or is it a very smart monkey ? ;) ). Having newsgroups would fit in nicely with the above but also make for a more lively development team when most know eachother.
