### ISSUE TITLE
Installer should install "PDF Help Files" documentation by default

### ISSUE THREAD

**Issue by Enlightenment-zz** [open-watcom/open-watcom-v2#1252]
The installer should automaticaly enable installing "PDF Help Files" by default.
I understand that a DOS or OS2 hosts may not want PDF files enabled by default,
thus conditionatlly enable PDF files for specific hosts, such as Windows & Linux only.

Currently, it's not obvious to a new user that they won't automatically get the 
PDF Help Files, because they have to drill down 2 menus to determine this box 
is unchecked by default.  Actually it wasn't obvious to an existing user either,
because I had to reinstall additional times to dig through the menus to find it.

My Watcom C/C++:
* Installed IDE = 2.0 beta Feb 29 2024 02:16:26 (64-bit)
* Installed Dir = C:\WATCOM

My Host O/S:
* Win10 Home 22H2 64bit

**Comment by jmalak** [comment]
Help files are install in host native format (on-line Help for tools) and PDF format is optional (not used by tools).

**Comment by Enlightenment-zz** [comment]
Thanks, but I already determined that information.

I have 2 issues with the current choice.

1) It's not obvious to someone that either newly or rarely installs Watcom that PDF manuals aren't installed by default.  If this choice was either in the top level install menu or the next menu down, but a person has to drill down 2 menus to discover the PDF manuals aren't installed by default.

2) In 2024, when Windows and Linux hosts typically have large hard drives, installing 12MB more of PDFs is almost nothing compared to the size of the hard drives.  My point is they should be installed by default on these types of host, because 12MB of drive use isn't missed by anyone in 2024.

**Comment by jmalak** [comment]
I understand your point, but this is not acceptable to the OW.
File size is not a clue.
The PDF type was not a standard part of WATCOM or earlier versions of OW distributions because the installer installs the online documentation used by the OW tools at runtime (there are a links to the content). Therefore, PDF will always be optional, as online documentation in native format must always be installed. A PDF version has been added as an off-line replacement for the online documentation and the printed postscript version.
For example, it is possible to generate an offline HTML version of any OW documentation, but it is only used for the OW Wiki. We can place the PDF documentation in a different place in the installer, but it will always be user selectable. The same problem exists with host and target platform selection, why to choose, when everything can be installed, etc.
The user always has to choose what they want to use, which is why PDF documentation is optional.
