### ISSUE TITLE
Please tag the latest release with a date as well

### ISSUE THREAD

**Issue by DarkShadow44** [open-watcom/open-watcom-v2#1257]
I'm maintaining the Arch Linux [AUR package for openwatcom-2](https://aur.archlinux.org/packages/openwatcom-v2) and ran into issue with packaging the latest version.

Currently the latest build is called "Latest-CI-Build" and "Current-Ci-Build" while the previous build is called "2024-03-01-Build".
It would be nice having the latest build tagged with a date as well so I have a permanent link that doesn't change when a new build is published.

**Comment by jmalak** [comment]
The "Latest-CI-Build" and "Current-Ci-Build" OW build are latest version after last change that cannot contains date in tag name because they are replaced after rebuild. Release build (permanent) is created during first build each month. If you are creating package then you should create it from Release build (permanent). "Latest-CI-Build" and "Current-Ci-Build" OW build are not created periodicaly they are triggered by changes in repository or manualy if needed.
I don't know how frequently you create the package.

**Comment by DarkShadow44** [comment]
Ah so I shouldn't package "Current-Build" / "Latest-Ci-Build" in the first place, but like "2024-03-01", even if that is a slightly older version... All I need for my package is a reasonably recent build that I can reliably package.
I thought when a new version releases, the Current-Build gets moved to a date, e.g. current build would be called 2024-03-19-Build. But I guess I just got a bit confused. Sorry to bother and thanks for the explanation!

**Comment by jmalak** [comment]
No problem. It is possible to automate extra build if it helps you because existing snapshot contains some additional information for debugging and some tools for additional architectures which is not part of standard installer content.
