### ISSUE TITLE
The compiler is limited to only 65535 entries in some cases.

### ISSUE THREAD

**Issue by MarekKnapek** [open-watcom/open-watcom-v2#1259]
Error message: `Error! E1145: Internal compiler limit exceeded, break module into smaller pieces`.

Discord [discussion](https://discord.com/channels/922934435744206908/922945502683758622/1222462838484897902).

Steps to reproduce:
 - `git clone https://github.com/MarekKnapek/mk_clib.git`
 - open `mk_clib\projects\ow2\mk_clib.wpj ` Open Watcom 2 IDE project file
 - build the `winnt\mkct.exe` project
 - or build the `mk_clib\app\mkct.c` C source file from command line

**Comment by MarekKnapek** [comment]
Oh I forgot, before any C compilation, you need to run the `m4` pre-processor. Run the `mk_clib\projects\gcc\build_m4.sh` file from `bash`. Or open the `mk_clib\projects\vs2022\mk_clib.sln` project in Visual Studio 2022 and build the `m4` project. You can download the `m4` pre-processor binaries for Windows from SourceForge from http://downloads.sourceforge.net/gnuwin32/m4-1.4.14-1-dep.zip and from http://downloads.sourceforge.net/gnuwin32/m4-1.4.14-1-bin.zip.

**Comment by jmalak** [comment]
Thanks for this additional notes.

**Comment by jmalak** [comment]
I did first analysis of code and it looks like that it is more complex issue then it looks like.
Generaly it looks like number of symbols overflows limit.
It is checked in compiler front-end that it is total number of used C symbols.
But this check should not be there, but it should check number of object module symbols which depend on output module format.
OW by default use OMF format and limit of single module symbols is 32767.
Because check is done in Compiler front-end it was used limit 65535 symbols because not all symbols is used in object module.
To fix the issue it will require to do check for number of symbols in code generator which is capable count number of symbols used by object module and know limits for each object module format OMF, COFF and ELF and is capable report it to compiler front-end.
The solution is to move this check to code generator which will report overflow if the limit of symbols used by object module will be exceeded. This fix issue with various output formats limits and need not limit number of symbols in front-end existing 
 way to fixed value without dependency on real symbol limit.
It will require to add new callback message which will signal the symbol number limit overflow and appropriate code to symbol output procedure to detect this limit overflow. Original check in front-end will be changed to new technical limits dictated by 32-bit memory limits for symbols allocation. But it will be probably much higher then existing limit. The main limit will be limit by object module format.

**Comment by winspool** [comment]
Thanks Jiri for the infos.

Is it possible to print the numbers of the used items
at the end of a compilation unit?

That might give a hint, why OpenWatcom is so slow for
the yarpgen testcase  (bug #1045)

**Comment by jmalak** [comment]
Number of symbols has nothing to do with performance.
for symbol names handling is used hash tables with appropriate hashing function.
The size of hash tables for different namespaces are
ID_HASH_SIZE                  241
MACRO_HASH_SIZE        4093
STRING_HASH_SIZE        1024

What sense have source file with by example 100 MB.
I am not interested in such cases.

**Comment by jmalak** [comment]
it is little bit strange application with one object file with size about 600 kB which is near maximum for OMF output format.
Be careful it take a long time a few minutes to compile mkct.c file. Linking is quick. Now compiler limits are is 1 milion of symbols.
Code generator was modified to check number of OMF symbols and report if limit (32767 symbols) is overflow.
Please re-check with latest version of OW compiler.

**Comment by MarekKnapek** [comment]
Works great, thank you.
