### ISSUE TITLE
how to cherry-pick from owp4v1copy?

### ISSUE THREAD

**Issue by ABratovic** [open-watcom/open-watcom-v2#137]
I was looking to revisit the wgml project and help it along.
The last update from perforce to owp4v1copy and on to the v2 wgml project was in August 2013 (P4 change 37505).
There has been quite a few wgml commits on perforce recently so I was looking at how to get all the changes into my branch of V2 starting with this one (P4 change 37512)
https://github.com/open-watcom/owp4v1copy/commit/8e7a88a5556a674013eac252b9464d6c9b4d1b57

Any suggestions welcome.

**Comment by jmalak** [comment]
To use cherry-pick is simple. First you must add owp4v1copy repository main branch as next remote branch to your working copy of V2 fork repository.
After that simply use cherry-pick and select commit from owp4v1copy repository branch and merge it to your development branch.

Anyway, I little cleanup wgml project in V2 fork that it is not same as P4 repository version.
It was necessary to ensure it is working properly on all platforms supported by V2 fork.
I am thinking to back-port some changes from V2 fork to P4 repository, but I have no much time for this task (low priority). It is necessary to be careful if you merge changes from P4 because some variables are renamed etc. I back-ported build system wgml stuff changes (to be working on 64-bit) to P4 for guys developping on old development system.
If you will have any question than use this issue to your questions (I will not close it).
