### ISSUE TITLE
the debugger has become unuseably buggy

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#156]
I've made one or more specific bug reports.  My intention here is to raise the issue more generally.  Am I the only person who uses the debugger (wdw.exe)?  Using the debugger has always been maddening with OW-v2 because it is so damned unstable and because you cannot change any of the configuration without all but ensuring that it will crap on you even more.  For example, you cannot even change the display of values to default to hex.  All of those problems exist in the release that I downloaded back in January 2015.

Sometime later, probably at the beginning of March, I installed the current 32-bit binary onto my laptop and the current 64-bit binary onto a development server.  None of the problems listed above are fixed, and now there's a new one, a SHOW STOPPER.  With the updated binaries, I can no longer climb stack frames.  The call nest list appears to respond to clicking the up and down arrows on the toolbar, but the text in the source code window doesn't change.  This means that if the debugger breaks on, say, an access violation, you can't click the up arrow to see who called the errant code.

This is not a specific bug report.  It is a note to raise an issue of regression testing.  It's fun to enhance code and to port it, but if you destroy the debugger in the process, you are going to destroy the product.  OW cannot be used efficiently to develop code without using the debugger.

Regression testing the debugger would both ensure that the product remains usable and be a good way to find out right away that you've fucked up code generation.  It is beyond my comprehension that no one is doing this.

Most, if not all, of the WDW bugs that make my life as an OW user hell are not due to incorrect code generation.  These bugs are of the kind that are caused by making changes carelessly.  For example, the instability that results as soon as configuration options are changed appears to involve incorrect array indexing (an offset is off by 1).

I would love to take on the task of debugging WDW as a contributor, and not a week goes by without the thought occurring to me.  But I am hopelessly swamped with other matters.  All I can do is to take some time to write a note like this in the hope that it will be of some use.  I have a great fear that OWv2 is being destroyed, if that has not already come to pass.  Today, OWv2 is not usable on either the 32 bit or 64 bit Windows platform.  Am I the only one who thinks that this is a serious issue?  How can OWv2 possibly attract new Windows users if the damn debugger is unusable?

**Comment by ArmstrongJ** [comment]
I'm using nightly 32-bit builds (which one, I don't recall) on a Windows 8 64-bit machine and a GNU/Linux machine (with wdw.exe under WINE), and I'm not seeing the symptoms you're reporting.  It seems to be working as well as it ever has.  I'm not disputing that you're seeing issues, but I can't seem to reproduce them.

You need to remember that there just isn't much manpower behind this project.  If you look at the contributors page here where it lists actual number of lines committed, you'll see that one person is doing almost all the work.  I've been contributing where I can (and usually in a mildly self-serving manner, but still...).  Because I'm not seeing bugs right now with the debugger personally, I've never looked at it much.  Of course, I don't know much about how it works, so I'll probably continue to avoid it and focus on implementing missing Linux library features or bug fixes and additions related to the Windows API.

I'm not sure accusing contributors of "destroying" Open Watcom is the best way to get someone to examine a bug.  If some of your earlier bugs haven't yet been addressed, it's probably again a manpower issue.  I get the feeling that Jiri, the main contributor, is focusing on getting 64-bit code generation up to snuff as his top priority, and I can't fault him for that.  It comes down to manpower issues and prioritizing all the many tasks and feature upgrades that are necessary to keep Open Watcom at least partially relevant.

Remember too that this is, technically speaking, a fork of Open Watcom.  Because it is open source, the original code will always be there if you want to avoid this fork.  I think people here have been pretty clear that this is a "development" version, and perhaps some components are not ready for production work.  I'm sure there wouldn't be a release of this fork (an actual release, not a nightly) with a completely broken debugger.

That said, I'll keep my eye out for any strange debugger behavior when I do use it.

**Comment by ideafarm** [comment]
What Jiri is doing excites me, and I know that the real issue is manpower.  I've used OW exclusively as my C++ development platform since before time began, and this continues.  I cannot be a contributor.  But I could be serving the project as an "alpha tester".  I literally cannot come current on OW because the debugger is utterly unusable.  If Jiri could work with me to get a couple of bugs fixed in WDW.EXE, I would be able to come current.  Once current, I could provide him with detailed, usable bug reports of any show-stopper bugs that I find, and I would be very willing to keep my 32 bit and 64 bit Windows development machines current so that my use of OW would serve as a vigorous regression test.  I am actively developing IPDOS (tm), which is a "piggyback operating system".  It's a relatively large system and it uses OW aggressively, so it is a good testbed.

If Jiri, or you, or any other contributor, is willing to work with me to get this going, my participation would help insure that OW remains usable on Windows.  With me essentially doing regression testing, contributors who are mainly interested in Linux would be able to "go for it" without breaking OW for me and for others (current and potential) who rely on OW to develop Windows applications.

Eventually, I want to become an OWv2 contributor.  Until then, I'd like to contribute as a Windows regression test site.  And if you or anyone is willing to hold my hand to help me take another crack at getting set up to contribute code fixes, I might be able to take on the task of debugging the WDW bugs that I can so easily reproduce, so that instead of writing bug reports that no one has time for, I might be able to provide code fixes.  I would love to do that.

**Comment by rdos314** [comment]
I use wdw all the time (as a remote debugger over TCP/IP), and I don't think it is terribly buggy. The only serious bug that is kind of irritating is that I need to step over the first line in a method, otherwise it won't break at the right place. I think this is due to the stack checking function. 

Although I admit I haven't built from source for a while and I'm using a build from 2014.

**Comment by jmalak** [comment]
I know that some features are broken. But now I am porting debugger to 64-bit host.
It is reason why we are in beta status, not all parts of OW2 fork must be working.
You can see where my current changes are located, it is in UI/GUI/AUI/TRAP/DIP/MAD and WD.
I don't understand what you expecting from me.
See discusion in issue #35. The similar discussion without any value, up to now you don't contribute anything valuable except that some errors are in debugger. 
!!! Yes it is true and we know there are some bugs !!!.
If you don't like OW2 fork then you don't need to use it. It is your freedom. 
You can use OW1.9 it has your quality requirements. 
OW2 fork doesn't untill will be released for production use.
If you wan't to contribute something valuable you are welcome.

**Comment by ideafarm** [comment]
AFAIK, OW1.9 doesn't work on Windows 7.  I was forced to migrate to OW2 when I began using Windows 7 for development.  Your fork is the only game in town for development on Windows.  That's why I've occasionally posted screams of pain in your repository.

As of last night, I have a Windows 2012 R2 virtual server (at Rackspace.com) set up for OW2 builds, and a build appears to have completed successfully.  I've also finally taken some time to become familiar with GitHub, so now I know what a "commit" is.  My plan is to debug the debugger myself.  Rather than send you bug reports, I will just offer the fixes to you.

I am still struggling with a battle in court and with the fact that IDEAFARM.COM does not yet generate any revenue.  Once I have revenue, I intend to become a serious contributor of bug fixes and regression testing.  All of the source code for IPDOS (tm) is about to be released as proprietary open source, and this is going to generate interest in OW2.  IPDOS (tm) will eventually be ported to Linux, but at this time requires Windows, so my involvement in OW2 will result mainly in QC that restores OW2 as a rock solid platform for developing Windows applications.  IMO, my focus on stability on Windows will complement your focus on porting to 64-bit and to Linux.

**Comment by jmalak** [comment]
I don't think that bug reports have no sense, it enable potential contributor to select some bug for fixing. Also we have history of bugs with discussion and with resolution. May be useful for regressions.
Porting debugger to 64-bit take some time, there are many parts, which will need some API modifications etc. Main problem to get real 64-bit debugger is to create new trap file for x64 architecture and enable expression processor to process 64-bit/128-bit integers. Now debugger is in phase when anything can be broken for some time. Untill we update all parts to work on 64-bit (not only compile) the testing and bug fixing is random. Also testing debugger can not be automated now. I a little more separate debugger engine (core) which can be used for various frontends. All this take time. I don't expect that some intensive testing have sense now. May be after a few month we will finished main change in all debugger components. Some testing of frontend could have sense because GUI/UI/AUI is now relatively stable.

**Comment by jmalak** [comment]
Anyway OW 1.9 works on Windows 7 (minimaly core command line tools) and I use it for building OW 2.0. But all new 64-bit support are not there. I mean WLIB, WLINK, WRC which now support PE32+ format.

**Comment by ideafarm** [comment]
What you are doing excites me totally, Jiri.  Keep doing it.  I will stay current with OW2 and will take a crack at finding the two or three bugs in WDW that make it unusable for me and/or really bug me.

**Comment by ideafarm** [comment]
I've just built OW2 from current source and released it to the Rackspace server that I use for development.  The "show-stopper" bug that caused me to open this issue appears to be fixed; I cannot reproduce it.  That was the only bug that was keeping me from staying current.  Now I'm going to start reproducing and eliminating the WDW bugs that bug me.
