### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by groessler** [open-watcom/open-watcom-v2#174]
Hi,

I'm trying to build OW on Windows. I've got Windows 7 in a VirtualBox and Visual-C 7.1.

I'm getting this:

c:\Users\chris\tmp\open-watcom-v2>type bootx.log

Microsoft (R) Program Maintenance Utility Version 7.10.3077
Copyright (C) Microsoft Corporation.  All rights reserved.

        if exist *.obj erase *.obj
        if exist *.gh  erase *.gh
        if exist *.exe erase *.exe

Microsoft (R) Program Maintenance Utility Version 7.10.3077
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -c -nologo -Zi -W4 -WX -MT -Fm -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -wd4244 -I. -I..\h -I..\..\watcom\h -I..\..\l
ib_misc\h -DBOOTSTRAP -D__NT__ -I. -Fowsplice.obj ..\..\builder\c\wsplice.c
wsplice.c
        cl -c -nologo -Zi -W4 -WX -MT -Fm -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -wd4244 -I. -I..\h -I..\..\watcom\h -I..\..\l
ib_misc\h -DBOOTSTRAP -D__NT__ -I. -Foclibext.obj ..\..\watcom\c\clibext.c
clibext.c
..\..\watcom\c\clibext.c(1309) : error C2220: warning treated as error - no object file generated
..\..\watcom\c\clibext.c(1309) : warning C4013: '_get_pgmptr' undefined; assuming extern returning int
..\..\watcom\c\clibext.c(2523) : warning C4013: 'GetModuleHandleEx' undefined; assuming extern returning int
..\..\watcom\c\clibext.c(2523) : error C2065: 'GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS' : undeclared identifier
..\..\watcom\c\clibext.c(2534) : warning C4013: 'vsnprintf' undefined; assuming extern returning int
NMAKE : fatal error U1077: 'cl' : return code '0x2'
Stop.

c:\Users\chris\tmp\open-watcom-v2>cl /version
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 13.10.3077 for 80x86
Copyright (C) Microsoft Corporation 1984-2002. All rights reserved.

cl : Command line warning D4002 : ignoring unknown option '/version'
cl : Command line error D2003 : missing source filename

c:\Users\chris\tmp\open-watcom-v2>

I didn't find the prerequisites required to bootstrap OW in the docs. If I missed them, please point me to them.

The Windows itself is a 64-bit installation. VC 7.1 doesn't support 64-bit, but for now, I don't need/want 64-bit support. I just want to build the compilers and compare them to versions built on Linux.

**Comment by jmalak** [comment]
We don't tested bootstrap with 32-bit Microsoft compilers, because you can use OW compiler on Windows for this task. We use Microsoft compilers only for 64-bit version.
I recommend to use OW 1.9 or 2.0 beta for bootstrap.

**Comment by groessler** [comment]
Ok, I've tried to bootstrap with OW 1.9. Seems to work, but I encountered an issue that wgml.exe is a 16-bit program which cannot be run on 64-bit Windows. I had set OWDOCBUILD to 0. The build hasn't finished therefore.

Is it documented somewhere that to build on Windows (32-bit) one cannot use Visual-C? Might be a good addition to the wiki.

**Comment by jmalak** [comment]
You are right, this info is not available in transparent form. 
I will review build guide and update it to be more transparent and add notes about other pre-requisity software necessary for building OW.

It has no sense to use for 32-bit build on OW supported platforms anything other than OW toolchain.
I don't suppose to use old 16/32-bit versions of Microsoft VC, because no gain from their use. 
I am checking OW build only with MS VC 2010 and 2012 Express. It builds with 32-bit version of these compilers.
We add support for other toolchains only for 64-bit build. 
Generaly we could add support for 32-bit compilers but it has sense only for platforms not supported by OW.

In setvars.bat scripts is comment that on 64-bit hosts you need DOS emulator, recommended is DOSBOX. I think that all 32-bit Windows support Virtual DOS Machine mode and has DOS emulator included, if not then DOSBOX can be used again.

**Comment by groessler** [comment]
Ok, using OW 1.9 on Windows the build went thru.

Thanks,
chris
