### ISSUE TITLE
Text Editor UI font issues

### ISSUE THREAD

**Issue by sparky4** [open-watcom/open-watcom-v2#206]
[20:47]	friend https://anonmgur.com/up/658874d4e600373e5f6ff167b4b82cbd.png
[20:47]	friend made it small to illustrate my point
[20:48]	friend	there's like 3 letters of space after Line:
[20:49]	friend	so the numbers get shoved off the edge
[20:49]	friend	and there's acres of room on the bottom bar that could be used to compensate
[20:49]	friend	thats not my font, thats poor ui design

from  my IRC to you

Just an improvement suggestion

the OS is XP
font is fixedsys excelsior 3.01 if that matters

**Comment by jmalak** [comment]
Status line have fix width (in characters) for each field.
It looks like the used font is wider then proportional font.
Anyway it will require to change size of fields on status line by font metric.

**Comment by jmalak** [comment]
The problem is hard to fix, because problem is caused by design.
You can change setup of "statussections" variable in weditor.ini file to fix this issue.
This parameter define start position of each section on status bar in points.Original line is
set statussections = 60 105 192 244
that you must multiply each number by some constant to do fields wider.

**Comment by sparky4** [comment]
this is not good....

**Comment by jmalak** [comment]
I understand, but existing solution is capable to solve the issue.
The solution must be independent on Operating system, must be same for Windows and for OS/2 Presentation manager. If anybody is interesting in this problem fix then can push a fix.

**Comment by jmalak** [comment]
It is now partialy fix by change d2d791529129a96151970781ba5d0f73a4d16667 in git repository
