### ISSUE TITLE
Fortan - compile an NT compatible Win32 Window

### ISSUE THREAD

**Issue by watfor-mike** [open-watcom/open-watcom-v2#221]
Thank you for the work you have done.

I am interested in using V2 to compile an NT WIN32 windowed application.

I've started simple, ie. with a hello world in a MessageBox.

There doesn't appear to be a way to compile the simple app.  The compiler seems to be installed correctly, I installed both the f77 and CPP versions for windows 64.  Watzee compiled correctly on the CPP compiler and ran under Windows 10, and the DLL test sample in the Fortran sub-directory compiled and ran also, but in a console (CMD) window .

The IDE has options for NT windowed apps, but seems to only function with CPP compiler.

So here's the questions;
1) Am I a clueless noob and missing something?
2) Assuming that #1 is not the case, is there an active effort to bring full WIN32 up to an operating level on the Fortran side?
3) How can I help?  I'm not a total noob, but not an expert either.
     i.) Looks like new .fi files would need to be generated with the correct pragmas for the Win32 functions, and likely a winuser.fi to start with to mirror the CPP side of the house like the 386 and WIN16 development.
    ii.) Does invoking the Fortran compiler/linker with the nt_win cause it to look for an NT sub-directory in all the directory structures like the CPP compiler/Linker, and other house keeping type of items about emmited defines and structure of the environment?

**Comment by jmalak** [comment]
If I understand your problem correctly then it is misunderstanding of WIN32 interface.
WIN32 has two main application interfaces GUI and Character based (console).
It depends on application design, because programming technique is diferent and it is not possible to recompile application for different mode without application change.
Take into account that all FORTRAN WIndows stuff (as .fi header files etc.) are for 16-bit Windows not for WIN32.
In the past Default Windowing (emulated character based mode in GUI) mode was possible for WIN32 but it was removed as useless (ineficient). This mode is still available in 16-bit windows where character mode doesn't exist.
You can still compile Defaul Windowing stuff for WIN32 in CRTL if you recompile OW CRTL with set OWDEFAULT_WINDOWING=1 environment variable and then compile character mode application as GUI application. But it is completely untested and I don't know if it is compilable/buildable now.

**Comment by watfor-mike** [comment]
Thank you for the quick response.

I found the WIN32 sample in the IDE Directory (sorry I posted before finding it) and I'm working through that now.  It compiled fine, now I just need to figure out what was done and work it into my knowledge base.  I see the special .fi files in the sample and it looks as if in general the Fortran is compiled to an obj, resources are added, and then it is treated like a  c program from there by using wlink.  Interesting stuff.

**Comment by jmalak** [comment]
OW support multi language environment.
You can combine FORTRAN, assembly, C or C++ modules in your application.
But it is necessary to respect each language interface.
I think it is described in OW programers guide in appropriate section.
Anyway all OW language libraries use same core C run-time library (CRTL) and math library.

**Comment by watfor-mike** [comment]
Thanks for all of the help.  I was able to get it running, and it will pop up a MessageBox in either a a Windowed WIN32 Application (even a character based program).

I went down a partial dead end with the wlink that the IDE puts in the makefile, but I was able to get WFL to work, but I expect to revisit wlink makefile with the ultimate expansion into a program.  

I ended up creating a winuser.fi that works for my ultimate goal on an nt_win compile.

I can display (and eventually handle) all of the various WIN32 buttons, and all of the WIN32 defined Icons in the Messagebox.

Runs under Windows 10.
