### ISSUE TITLE
Current build segfaults on Linux while building cpplib

### ISSUE THREAD

**Issue by andikleen** [open-watcom/open-watcom-v2#237]
building on linux-x86-64 I end up with

c++ sqrt.obj
c++ tan.obj
c++ tanh.obj
%create cplx7s.lbc
bwlib -q -b-c-n-pa -s-t-zld cplx7s.lib @cplx7s.lbc
= 08:30:40 /home/andi/compiler/open-watcom-v2/bld/cpplib/contain/generic.086/mc =
c++ wcexcept.obj
c++ wchash.obj
Segmentation fault
Error(E42): Last command making (wchash.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 512
Build failed

**Comment by jmalak** [comment]
Thanks for bug report.
Yes, C++ compiler 64-bit Linux build is still broken.
It looks like compiler code is not portable to 64-bit Linux, but works on 64-bit Windows.

**Comment by Graham-stott** [comment]
builds ok with gcc 4.9 but fails with 5 or later.

**Comment by Graham-stott** [comment]
now gets past wchash.cpp failure using latest gcc 5 branch  but fails in wv some gui headers not found  due to resent gui changes

**Comment by Graham-stott** [comment]
now builds on linux with latest gcc 5 build

**Comment by jmalak** [comment]
Thanks for your note about GCC 5.

**Comment by andikleen** [comment]
On Sun, Apr 10, 2016 at 09:39:10PM -0700, Jiří Malák wrote:
> Thanks for your note about GCC 5.

I was already using gcc 5. I have doubts it is really fixed.

-Andi

**Comment by Graham-stott** [comment]
My mistake 4.9 thought I switched to use  all 5.x compiler to build 

I can confirm builds still fail same way in cpplib.

**Comment by jmalak** [comment]
there are two known problems, first is buggy C++ run-time library created by 64-bit Linux version of C++ compiller and bug for 64-bit Linux version of C++ compiler if build something. What you reported is second bug and sometime it apears some time disapears. No problems with 64-bit Windows version. It is probably related to long type size.

**Comment by andikleen** [comment]
On Mon, Apr 11, 2016 at 09:25:44AM -0700, Jiří Malák wrote:
> there are two known problems, first is buggy C++ run-time library created by
> 64-bit Linux version of C++ compiller and bug for 64-bit Linux version of C++
> compiler if build something. What you reported is second bug and sometime it
> apears some time disapears. No problems with 64-bit Windows version. It is
> probably related to long type size.

I did some investigation and it appears some corruption related to the
(custom) memory allocator used for types.

One idea I had to track it down was to make valgrind work for
openwatcom binaries. This would need some annotations so that
valgrind can understand these custom allocators.

-Andi

**Comment by jmalak** [comment]
It help us significantly if anybody do some investigation of any OW problem. I can help you with anything what I know, but it doesn't mean that I understand all things in OW. The main problem for me is that I am not much familiare with debuggers for GCC generated code. The C++ compiler problems are related to LP 64 mode compilers as GCC and CLang. It signal the C++ compiler code is not always well portable to 64-bit LP64 compilers. I recommend to not use pre-compiled header files during investigation or debugging, it is not tested on 64-bit LP64 platforms. I did some atempt to localise source of problem and it looks like it have something with RT info for run-time code for C++ libraries. C++ compiler must create various structures for appropriate target (16 or 32 bit) on the fly, Prototypes for these structures can not be simply defined in C++ compiler code because size of pointers on each architecture is different, also some field size in these structures is dependent on target architecture, target OS and can be compiler tool chain specific. Too many variants. I probably don't did all change portable way for LP64 model even if it is fixed on 64-bit Windows. May be it is one stupid mistake I don't know.
