### ISSUE TITLE
Any plan to maintain jwasm and jwlink? [Question]

### ISSUE THREAD

**Issue by fithisux** [open-watcom/open-watcom-v2#238]
Openwatcom has a linker and an assembler.

Is there any plan to drop them in favor of jwasm and jwlink while direct maintenance there?

**Comment by jmalak** [comment]
Why you think that we should drop current wasm and wlink and compicate our live by jwasm and jwlink?
jwasm and jwlink are not compatible with OW wasm and wlink.
jwasm and jwlink was developed as standalone tool to be compatible with appropriate MS tools and some important OW stuff was removed or is missing.
We are able to host source code if any interest.

**Comment by fithisux** [comment]
You are very clear. Thank you for the info.

On Mon, Feb 22, 2016 at 6:59 PM, Jiří Malák <notifications@github.com>
wrote:

> Why you think that we should drop current wasm and wlink and compicate our
> live by jwasm and jwlink?
> jwasm and jwlink are not compatible with OW wasm and wlink.
> jwasm and jwlink was developed as standalone tool to be compatible with
> appropriate MS tools and some important OW stuff was removed or is missing.
> We are able to host source code if any interest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-watcom/open-watcom-v2/issues/238#issuecomment-187267116>
> .
>



-- 
Dr. Vasileios Anagnostopoulos (MSc,PhD)
Researcher/Developer
ICCS/NTUA 9 Heroon Polytechneiou Str., Zografou 15773 Athens,Greece
T (+30) 2107723404 M (+30) 6936935388
E vanag@mail.ntua.gr<mailto:vanag@mail.ntua.gr> www.ntua.gr<
http://www.ntua.gr/>

**Comment by jmalak** [comment]
I am open to any discussion, but it looks like development of JWASM continue at
https://github.com/Terraspace/HJWasm
JWlink has no follower.
If some interest from comunity, we are able to update LINK driver for wlink to be compatible with up-to-date MS linker (by options) and add support for PE+.

**Comment by rdos314** [comment]
I've used the 64-bit code generator in JWASM, but it doesn't work properly with mixed memory models, so I'd prefer if 64-bit code generation is added to WASM instead. The JWASM maintainer didn't think my problem with the code generator was something he needed to solve (= poor support of JWASM).

**Comment by jmalak** [comment]
Are you able to give me some details or sample to better understand your problem.
I am planning to extend ORL/OWL projects, WASM and WLINK for 64-bit.

**Comment by rdos314** [comment]
If you want something to play with, I have a mixed-mode RDOS device-driver. It's kind of strange in several ways because of problems with JWASM, but last I checked it at least compiled and worked. Link: http://www.rdos.net/svn/trunk/kernel/os/longmode.asm. It does require a few other files as well, but those are also in the source tree. Especially the device-driver coding is strange, but also the switch between 32-bit and 64-bit code somewhere in the middle of it.

**Comment by jmalak** [comment]
Thanks for link to source. 
I understand that code is not ideal and must fix some problem in JWASM.
But it could be good demonstration of JWASM problem.

**Comment by rdos314** [comment]
When I think about it further, I had to tweak the interface in RDOS because I couldn't have some code 0-based (the 32-bit part) and other parts at a fixed location (the 64-bit part), as this generated a padding up to the fixed location, which in my case was over 1MB. I think that was the major problem. I can imagine I could do a lot of interesting things with 64-bit code in WASM, so I'm looking forward to that.
