### ISSUE TITLE
"arning! Malware detected. Download at your own risk." https://sourceforge.net/projects/openwatcom/files/current-build/

### ISSUE THREAD

**Issue by XVilka** [open-watcom/open-watcom-v2#262]
Check pls this link https://sourceforge.net/projects/openwatcom/files/current-build/
(anyway, looks like it wasn't updated for a long time). It's possible to upload those builds at github as a 'release'.

**Comment by jmalak** [comment]
As soon as I will finish update Watcom debugger to work on 64-bit host and fix all known problems with Debugger I will create new release. I was using Sourceforge due to statistic of download is available. I will check if GitHub has some similar info available and if yes then no problem move distribution to GitHub as releases.

**Comment by jmalak** [comment]
Anyway it is some Sourceforge enhancements to mark distribution by "Malware Detected" without any note to project administrator.

**Comment by XVilka** [comment]
No longer valid.
