### ISSUE TITLE
Change the license of Open Watcom

### ISSUE THREAD

**Issue by yuhong** [open-watcom/open-watcom-v2#271]
From the license:

"7. Versions of the License. Sybase may publish revised and/or new versions of this License from time to time. Each version will be given a distinguishing version number. Once Original Code has been published under a particular version of this License, You may continue to use it under the terms of that version. You may also choose to use such Original Code under the terms of any subsequent version of this License published by Sybase. No one other than Sybase has the right to modify the terms applicable to Covered Code created under this License."

This would make it easy for Sybase/SAP to release a new version of the license that is DFSG-/FSF-free. Do anyone have contacts at them that can ask about this.

**Comment by ArmstrongJ** [comment]
I'm pretty sure Sybase had been asked in the (now distant) past and refused just because they didn't see the point.  There is a "draft" version 2 of the license, but I'm guessing it can't just be adopted if it hasn't been adopted already.  However, if someone really thinks they can convince Sybase otherwise, give it a try!

One thing to remember, though, is that Sybase doesn't hold copyright over *all* of Open Watcom any longer.  Much of the current system has new files that are "Copyright Open Watcom contributors" with no attribution to Sybase.  Changing the license outright to something that isn't just a follow-on to the Open Watcom Public License might be tricky.

**Comment by yuhong** [comment]
The non DFSG-free problem is probably the most important problem.

**Comment by LocutusOfBorg** [comment]
Virtualbox Debian Maintainer here.
I would strongly support changing some bits of the license, we are trying again to get Vbox in Debian and Ubuntu main, and license is still a big issue.
You might want to read some analysis of the license and its problems here
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=376431

and the Ubuntu effort to have virtualbox in main here
https://bugs.launchpad.net/ubuntu/+source/virtualbox/+bug/1605337

thanks!

**Comment by austin987** [comment]
Winetricks/wine developer here.

Openwatcom would be useful for win as well to be able to add tests for win16 code, but the current license and lack of availability in Debian/Ubuntu and other distros has prevented this. A more OSS friendly license would be greatly appreciated!

**Comment by michael-thayer** [comment]
VirtualBox developer.  I wonder whether Sybase could publish some statement clarifying their intents in the licence which would still be good enough for Debian.  I imagine that would be easier for them than changing the licence.  Of course this would not make sense unless Debian says beforehand that they could live with this.

**Comment by LocutusOfBorg** [comment]
I can't speak for the community, but I personally think a clear statement clarifying the situation might really allow me to put a comment on the copyright file, with a reference on that statement, and I think ftpmasters will probably reconsider the license for the specific case.
But unfortunately I can't  be sure without reading the statement, and without an ftpmaster authoritative answer.

**Comment by michael-thayer** [comment]
I would suggest starting by asking the ftpmasters what sort of a statement - if any - would satisfy them, and then asking Sybase if they could consider that.

**Comment by LocutusOfBorg** [comment]
https://lists.debian.org/debian-devel/2016/08/msg00003.html
I started a discussion here

**Comment by LocutusOfBorg** [comment]
Hi, seems like we can't accept a statement, because the license is too contradictory and problematic, but the nice thing is that you don't have too many relicensing issues
https://lists.debian.org/debian-legal/2016/08/msg00001.html

"As a consequence, it should be super-easy for Sybase to fix all the
licensing issues in a flash, *provided* they are willing to do so.
They just have to issue a statement where they declare that they
elect the Expat/MIT license [3] to be the next version (2.0)
of the "Sybase Open Watcom Public License": the OpenWatcom
compiler would instantly become available under the Expat/MIT license.
Or maybe they want to choose the Apache License Version 2.0 [4]..."

**Comment by ArmstrongJ** [comment]
As I stated, there is a [version 2 of the Open Watcom Public License in draft form (warning: PDF link!)](http://download.xskernel.org/docs/licenses/watcom-2-redline.pdf) that Sybase never adopted.  Someone needs to speak with them, but, again, they may be unwilling to bother with it.  Additionally, I'm not sure many of the Open Watcom developers here care all that much or they wouldn't be working on Open Watcom in the first place.

The big problems with the license are some vagueness surrounding distributing source (it's currently interpreted similar to the GNU AGPL), some patent indemnification language, and specification of a venue for legal matters.

Regardless of the Debian's stance, the license is approved by the [Open Source Initiative](https://opensource.org/licenses/Watcom-1.0) as being a valid "open-source" license.  If it doesn't show up in Debian repos, I'll survive.  Apparently it's causing issues with VirtualBox, but that doesn't really directly affect this project.  

Changing the license would have to be done carefully.  Open Watcom isn't just a "little compiler project" like GCC.  It's a suite of compilers, a runtime library, and whole pile of development tools.  Using any sort of viral license would be exceptionally bad as it would preclude use of the runtime library in projects with alternative license terms.

**Comment by michael-thayer** [comment]
I suspect that the updated draft would not satisfy Debian either.  How actively is Sybase working on the code base?  If they have effectively let go of it then a reasonable argument (which may well still not be good enough for them) would be that changing to an MIT licence or similar would just be the last logical stage of letting go.  Other companies have done the same in similar situations.

**Comment by ArmstrongJ** [comment]
Sybase has not, to my knowledge, contributed any code since the project was open-sourced; they only provide some infrastructure and Perforce licenses to mainline Open Watcom development (which stalled out years ago).  

Sybase would need to specify that "The Sybase Open Watcom Public License Version 2 is the MIT License," as an example.  _They do not hold copyright over all of Open Watcom_, and they cannot unilaterally "change" the license.  The project's license would need to be upgraded to OWPL v2, which might happen to be worded exactly as an MIT, BSD, or Apache license.  I'm not particularly concerned with the Debian project's particular misgivings about this license, though.

**Comment by LocutusOfBorg** [comment]
that would fix every issue I think

**Comment by owainkenwayucl** [comment]
I've been looking at the wording of the license and trying to work out what implications clause 2.2. has if you distribute binaries built with the compiler (mostly for my own interest because I have no intention of doing so, I just use it to do some hobby programming on a FreeDOS PC in my free time).

It seems to me that if you distribute a binary built with the compiler it will contain libraries, run-time etc which would make it deploying portions of the "Covered Code", triggering all the source redistribution clauses.

Overall this means that although you can technically use the compilers for "non-personal/R&D" use, you can't really in practice?

Am I reading this correctly or am I just being really license correctness paranoid?

**Comment by sskras** [comment]
@ArmstrongJ:

> Sybase [...] _They do not hold copyright over all of Open Watcom_, and they cannot unilaterally "change" the license. 

Jeff, do you mean the new code from the post-Sybase contributors, individual persons here?  

If they are required to approve changing the OWPL v1.0 into one with different name (which I believe to be rational), then what is the reason / legal mechanism that would allow to avoid such aprovement when increasing the version number of OWPL?  

My guess is that _any_, even smallest change (such as version) in a license obtains the same requirements.  So contacting individual persons who have contributed would be still required (IMHO).

**Comment by ArmstrongJ** [comment]
I should clear up what I meant.  To the best of my knowledge, all files in Open Watcom are under the OWPL version 1 _or greater_.  Sybase indeed doesn't hold copyright over a significant portion of Open Watcom at this time, but, if they were to change the license by saying "OWPL version 2 is the modern BSD license," there wouldn't be much problem.  Even files on which they do not hold copyright contain the "or greater" clause.

The problem is, though, that Sybase has to change the license, and they have never seemed interested in doing so.

**Comment by michael-thayer-vb** [comment]
Is anyone known to have asked them recently, and if so, was there any answer?

**Comment by ArmstrongJ** [comment]
I don't think anyone's asked in a long while.  Obviously people contributing here aren't overly concerned with the license.

**Comment by bmanga** [comment]
> Obviously people contributing here aren't overly concerned with the license
While that may be true, that does not necessarily mean that the current license is any good for the project. There have been multiple instances of people complaining that the current one prevents them from using/distributing OW, and that probably negatively affects the number of new contributors willing to get on board.

**Comment by ArmstrongJ** [comment]
I was only trying to point out that most people contributing aren't actively trying to get Sybase to update the license.  If someone would like to try to start that process, they should.  Expecting someone else to do so, though, is the wrong strategy.

**Comment by bmanga** [comment]
Sorry, I misread your comment!

**Comment by sskras** [comment]
@bmanga,
> Does anyone actually have any contacts at SAP from the ex-Sybase team?

I think I could try to find some as our company is a client of SAP.

@ArmstrongJ, 
> Sybase would need to specify that "The Sybase Open Watcom Public License Version 2 is the MIT License," as an example. [...] The project's license would need to be upgraded to OWPL v2, which might happen to be worded exactly as an MIT, BSD, or Apache license. 

What do you think about **Apache License 2.0** specifically?  Is it nearer to the OWPL v1 by its spirit than MIT or BSD one?

Sometimes I follow the blog of Kyle E. Mitchel, an I.P. lawyer who specializes in open source software.  Already for several years he discourages from using MIT esp. in regard to patent handling (which I believe to have even higher relevance in the case of a corporation being involved).

But today I found even more points being addressed against the MIT and BSD:
https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html
(though the article is introducing another, next-lawyer-gen permissive license called _Blue Oak Model License 1.0.0_) 

So if a widely known permissive license is required for the change, and if *Apache 2.0* doesn't have bold contradictions with the spirit of OWPL v1, then it would be nice to avoid using MIT or BSD here.

Thoughts?

**Comment by yuhong** [comment]
One caveat is that it is not GPLv2 compatible.

**Comment by sskras** [comment]
Yes.  But maybe _Blue Oak Model License 1.0.0_ is GPLv2 compatible.

PS. https://www.froebe.net/blog/2013/06/28/call-for-sap-to-release-watcom-c-open-watcom-to-an-open-source-foundation-apache-foundation/

The URL in the author's comment is dead:

> Jason L Froebe
> JUNE 28, 2013 AT 3:20 PM
> http://scn.sap.com/message/14163307

If that was the petition or just a question in forum, it's interesting what was the response.
But I found the interview with Terry Orsborn:

https://blogs.sap.com/2016/01/11/21-years-and-counting-why-sap-is-an-employer-of-choice-for-terry-orsborn/

> Terry Orsborn is director of product marketing for the SAP HANA platform, and is responsible for product messaging and positioning, launches, and extending SAP HANA to net-new audiences through partner and customer marketing initiatives. [...]
> 
> **What brought you to SAP? What did you know about the company prior to working here?**
> 
> I came to SAP through a series of acquisitions. Back in 1994, I worked for a company called Watcom, where we were focused the Watcom C compiler and Watcom SQL DB 

So I am trying to contact Terry on Linked In.

**Comment by adrelanos** [comment]
Any update? Anyone tried to get in contact indeed and was able to contact someone?
