### ISSUE TITLE
borland's _seg

### ISSUE THREAD

**Issue by sparky4** [open-watcom/open-watcom-v2#279]
https://github.com/sparky4/16/blob/master/src/lib/types.h#L46

https://github.com/sparky4/16/blob/master/src/lib/16_ca.c
https://github.com/sparky4/16/blob/master/src/lib/16_ca.h
seen here opwn watcom do not have a direct translate

https://github.com/sparky4/16/blob/master/src/exmmtest.c#L48
is my work around but it cannot be implemented in typedefs....
hmmmm

also
coreleft();
https://github.com/sparky4/16/blob/master/src/lib/16_mm.c#L802
and
farcoreleft();
https://github.com/sparky4/16/blob/master/src/lib/16_mm.c#L825

equivalents?

**Comment by jmalak** [comment]
I don't understand what you mean by direct translate?
OW is able to do anything with pointers, but something stupid as Borland _seg no.
you can use macros to simulate _seg by OW based pointers or by MK_FP or by :> operator.
OW has only pointers capable to do pointer arithmetic. You should use __based( segment variable) type of based pointer as replacemnt for _seg.

By example you can typedef based pointer as svector_ptr type pointing to svector type
typedef svector __based(segment) *svector_ptr;
I think you could change your code to not use coreleft and farcoreleft functions or you must implement these functions.

**Comment by jmalak** [comment]
I think little bit about your problem. You should use following prototype for memptr.

typedef unsigned short memptr;         // it will contains segment value (as Borland _seg)

Usage of it

	if(!CA_FarRead(handle,MK_FP(*ptr, 0),size, mm))

You could replace all _seg usage by this without problem, because _seg construct have no any advance against this. This construct is more portable because something like MK_FP have each 16-bit compiler.
Usage of OW based pointers have no much sense, because they are based on offset arithmetic not on segment as Borland _seg.

**Comment by sparky4** [comment]
ok! 
let m try it out

**Comment by sparky4** [comment]
my memptr is defined already ... 

how do i use :>?

typedef unsigned short _seg; seems good for _seg?

**Comment by jmalak** [comment]
Take into account tha based pointers are near, hold only offset part of far pointer and assume segment part is known for compiler (defined by some variable, constant etc.).
Borland _seg pointers are holding only segment part of far pointer and assume 0 offset.
Therefore it is hard to do similar construct in OW by based pointers. 

declaration as 
typedef void __based(__self) * memptr;
has no sense, because it is pointer to segment where memptr is defined. __based(__self) has sense with structure members when takes segment part from its parent.

usage of :> operator is simple  segment :> offset it create appropriate far pointer.

I think there are two posibility to be able use both compilers.
1. replace _seg pointers by far pointers (but it not save memory, each _seg pointer will be doubled in size)
2. hold segment value as unsigned type and convert it to apppropriate pointer type on usage

**Comment by sparky4** [comment]
:> seems cool!
ok
https://github.com/sparky4/16/blob/master/src/lib/types.h#L46
here is the new definition and it works better!

i am thinking of 2. of the _seg conversion

the part that is throwing me off is 
https://github.com/sparky4/16/blob/master/src/lib/16_ca.c#L77
those things

**Comment by jmalak** [comment]
You should change

#ifdef __WATCOMC__
typedef void __based( void ) * memptr;	////old //----typedef void __based(__self) * memptr;
typedef unsigned short _seg; // it will contains segment value (as Borland _seg)
#endif
#ifdef __BORLANDC__
typedef void _seg * memptr;
#endif

to

typedef unsigned memseg;

memptr should be replaced by memseg in code.

on usage where you need pointer convert memseg type (segment) to far pointer by
MK_FP(segment value, 0)

It should be compatible with both compilers

**Comment by sparky4** [comment]
i am looking for same functionality as the borland compiler ^^; ok i can try it soon...

**Comment by jmalak** [comment]
_seg have no replacement in OW
details why it is not possible is here https://github.com/open-watcom/open-watcom-v2/issues/279#issuecomment-244587566

**Comment by sparky4** [comment]
ok thank
