### ISSUE TITLE
Help Desk for New Contributors (Problems building Open Watcom from OW source).

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#28]
If you have downloaded the source code for Open Watcom and are having trouble building OW for the first time, please post details here and someone will help you!

**Comment by pulkomandy** [comment]
Hi,
I am trying to get Open Watcom running on the Haiku operating system (www.haiku-os.org). I have fixed some initial issues, and currently I'm stuck with this problem:

    /sources/openwatcom-2.0.0/bld/orl/omf/c/omfmunge.c:89:5: warning: implicit declaration of function 'stricmp' [-Wimplicit-function-declaration]

Haiku has strcasecmp. I see there is a condition on _BSD_SOURCE to use that at the top of this file. However I don't know where I should be adding the _BSD_SOURCE define. Is there a way to add it to the host cflags somehow in the build system?
(I am using gcc and have set OWTOOLS=GCC in setvars.sh)

**Comment by jmalak** [comment]
Thanks for bug reporting.
It is now fixed in git repository 7d23ba88ff2a81660b2a48e4b73d2fcbcb36b837

**Comment by pulkomandy** [comment]
Hello again,
This seems to work and the build gets further.

Here are my changes so far: https://bitbucket.org/haikuports/haikuports/src/8dd8acc035c080fe894b74923eb1af4c08640d58/sys-devel/openwatcom/patches/openwatcom-2.0.0.patchset
(you probably don't want to apply all of it, yet, but some parts may be relevant).

My _cmdname implementation returns the full path to the executable and seems to work ok. However, bwasm fails to run because it can't open its messages (in the MsgInit function). I have tried to uncomment the -DUSE_TEXT_MSGS flag in master.mif for wasm, which seems to work. However build then fails in a similar way when running bwlink.

On Haiku exectuables are ELF files. While we do support something similar to Windows resources (https://haiku-os.org/legacy-docs/bebook/BResources.html), I don't think Watcom is making use of that. How are resources handled in that case and what is the right way to build the bootstrap tools (bwasm, bwlink) with debug information, so I can investigate this more easily?

**Comment by jmalak** [comment]
If I understand Haiku correctly then Haiku is not UNIX derivate.
It is hard for me to say how big effort will be necessary to port Open Watcom to Haiku, because my knowledge about Haiku is zero.
OW is ported to Linux, but not to BSD (it can be only run as Linux executable on BSD over Linux compatible layer).
OW can be build on POSIX systems but there can be some specific problems, which need fixing.
For OW is Haiku new OS and it requires to create full build environment for new OS (local.mif make file).
What filesystem separators Haiku use? Is filesystem case sensitive or in-sensitive?
What C/C++ compiler is used as system compiler?
For bootstrap tools build clibext.c/clibext.h must be ported to Haiku OS.

Anyway debug version of bootstrap tools can be build by command
builder boot OWDEBUGBUILD=1
in appropriate project directory, by example for WASM it must be run in bld/wasm.

**Comment by pulkomandy** [comment]
Hi,
Haiku is not (directly) UNIX derivative but it is POSIX compatible. I am one of the main developers of Haiku, but have little knowledge about the OpenWatcom build system. We should be able to work together on this :). My porting attempt so far is defining __UNIX__ (which gets most of the clibext building) and overriding parts that create problems as I find them (for example the /proc filesystem doesn't exist on Haiku so I had to rewrite _cmdname as you can see in the patch).

The filesystem uses / as a separator and is case sensitive. I'm using gcc 4.8.4 (we also have gcc 2.95.3 but I think it is better to not try using that).

Should I create a separate issue for this, or is it fine to continue here?

**Comment by jmalak** [comment]
I think that better will be to create issue for HAIKU OW port.

**Comment by jmalak** [comment]
I already created issue  Port OW to HAIKU OS #138
