### ISSUE TITLE
feature request: compiler flag to indicate CS is pegged to DGROUP

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#292]
There is compiler flag -zdp to say that DS is pegged to DGROUP.

I propose a compiler flag -zcp to say that CS is also pegged to DGROUP.

This would help with compiling COM and RAWBIN executable formats.

If you specify both -zdp and -zcp, the compiler could assume that DS = CS at runtime (and any custom code I write would enforce that), and emit references to CS instead of register loads with segment relocations for DGROUP symbols where a segment value is needed.

Near to far pointer conversion with -zdp and -zcp:

_dos_setvect(0x24,(void far*)intproc);

Instead of emitting a function call to push/load seg intproc_ and offset intproc_, it could instead push/load CS:intproc_

Inline assembly that references the seg of a symbol in DGROUP:

mov    ax,seg symbol
mov    bx,offset symbol

Could be compiled to:

mov    ax,cs
mov    bx,offset symbol

seg references to anything other than symbols in DGROUP should produce a segment relocation as normal.

I would be willing to try implementing this in my branch before submitting a patch.

EDIT: Actually, if DS = CS as described, it could emit mov ax,ds just as well.

**Comment by joncampbell123** [comment]
Hold on,

Perhaps it's better to say that -zcp could assume that CS = DGROUP, and therefore near to far pointer expansion for the code segment could load CS instead of a segment relocation.

For -zdp, perhaps that and another compiler flag could say that any near to far pointer expansion for data should load DS instead of a segment relocation.

**Comment by joncampbell123** [comment]
This is of course, for the small memory model only.

**Comment by rdos314** [comment]
I'd be careful about assuming that DS (or CS) is loaded with the value of the combined segment, because this might not always be the case. For instance, RDOS device drivers uses the small memory model and the zdp flag, but the initialization code is run with another CS loaded, so changing mov ax,SEG code to mov ax,cs would break things. Same for mov ax,SEG data, as this might be done in order to load the correct selector, In fact, RDOS device drivers require that these remain as relocations so they can be fixed-up by the linker.

**Comment by joncampbell123** [comment]
I understand that, assuming that by default would break existing code. I would like to add a compiler option to load DS instead of DGROUP when DS is pegged to DGROUP, and another one to assume CS is pegged to DGROUP and to load CS instead of DGROUP.

**Comment by jmalak** [comment]
I don't understand why you use -zdp option in small model where DS is supposed to be near DATA segment. Any part of code which manipulate with DS must restore original value. May be you should try to use -r option to preserve segment registers, no need reload it from DGROUP.
This request can not be acceptedd because it breaks architecture logic and do any code incompatible with CRTL etc. Code generator always suppose Code segment is different from Data segment and CS can not be pegged to anything except own CODE segment. What you want is rarely task for linker to put code into DATA group to ensure CS=DS, but generated code cannot assume this.

**Comment by joncampbell123** [comment]
Thanks for your feedback. I think it's important not to break things. I got what I wanted anyway by writing my own solution to patch the OBJ file after compile.

https://github.com/joncampbell123/doslib/blob/master/fmt/omf/omfsegdg.c

**Comment by joncampbell123** [comment]
Perhaps another way to say what I'm asking for is that the "wcl" tool has a -mt flag to say that you're linking for a tiny memory model. Perhaps .COM targets could compile with -mt instead of -ms. The compiler would otherwise act as if the -ms (small model) but would refer to CS instead of DGROUP. Could that be done?

**Comment by jmalak** [comment]
wcl is driver for OW tools therefore not all wcl options are passed to OW tools.
The -mt option is not real option for anything it is synonym for small memory model (compiler) and .com format (linker) and used starup code (CRTL) must ensure initialization of all segment registers.

Code generator is designed to follow Intel architecture concept when CS register is used for code segment reference and DS/ES for data segments reference. SS segment is pointing to stack segment.
Near data segments group is DGROUP and all near data are part of DGROUP group. Linker is responsible to do all segments and DGROUP allocation and symbols relocation. OW code generator is not capable to do reference to near data in DGROUP by CS register (only for data in code segment).
If you want to change this behaviour you must redesign code generator and do special version of CRTL for this behaviour.
