### ISSUE TITLE
Dialog box in text-mode debugger not working

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#295]
A few days ago the "Running" dialog came up in the text-mode debugger, but now it no longer works. In the windowed debugger, it still works as expected. 

When checked it in the debugger, GUICreateDialogFromRes() fails in GUIXCreateDialog() in guixdlg.c.

**Comment by jmalak** [comment]
Thanks for bug report. I will fix it ASAP.
Probably it is related to changes in wres project.

**Comment by rdos314** [comment]
Here is more detailed info of where it goes wrong:

guirdlg.c: GUICreateDialogFromRes()
guirdlg.c: Template2Dlg()
Fails on: ok = (size >= (data - d) );
data - d = 0x3F
size = 0x33

So it is the size that is too small in Template2Dlg(). 

I built it with your last checkin.

**Comment by jmalak** [comment]
The problem is with packed/unpacked structures for resources.
I reworked all GUI tools which are used for resource manipulation, but gui project is not finished yet.
I am now changing gui project to use wres library for reading DIALOG and MENU resources. wres library read resources data to unpacked structures, but existing code is wrong because suppose packed structures.

**Comment by jmalak** [comment]
it should be fixed by dc801b82e63dbe0e2eade9130787bd7fdd81cc89 commit

**Comment by rdos314** [comment]
Yes, it works now.
