### ISSUE TITLE
Feature request: intrinsic functions to test CPU flags, for use in if() statements following inline assembly (__asm or pragma aux)

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#315]
I would like to be able to do something in an __asm block (like some INT 21h functions) then after the ASM block, have an IF statement execute it's contents if CF=0 (carry not set), ELSE do something else CF=1 (carry set).

Currently you have to write the __asm block to set a local variable that the IF block tests, which is a bit redundant.

The intrinsic when used with if/while/do would boil down to a conditional branch instruction (or equivalent if necessary).

My primary reason for this is that I am writing some defines and macros for use in DOSLIB with writing VxD drivers and much of the VxD calls are register based. While I can cover for the register input/output with #pragma aux, many of the calls signal error by setting CF=1. A few calls return the result by whether or not ZF (zero flag) is set or cleared. I would like to be able to do this:

    __asm {
        mov ebx,someHandle
        int 20h ; VxDCall dddd,ssss
        dw 0x0004 ; Test_Sys_VM_Handle
        dw 0x0001
    }
    if (__x86_ZF()) { /* at this point, test ZF and enter this IF block if set */
        /* do something because someHandle is system VM */
    }
    else {
        /* do something else */
    }

How easy would it be to add this?

**Comment by joncampbell123** [comment]
I'm fully aware that I could write #pragma aux to use 386 instructions setz/setc and so on to provide a return value in AL, but that seems redundant to set AL by CPU flags, compare AL against zero, then branch.

**Comment by joncampbell123** [comment]
The int20h dw...dw... thing probably needs explanation. Within the Windows 32-bit kernel (Windows 3.0 386 enhanced mode and later) INT 20h is treated as a VxDcall instruction that Windows expects two WORDs to follow. These two words are the device ID (which VxD to call) and the service number (index into the VxD's service table). This is how VxDs call from one to another. For performance reasons, the full lookup is only done once when a VxDcall is first executed, after that Windows patches over the VxDcall with a CALL FAR [ptr] instruction to the call target.

**Comment by jmalak** [comment]
OW __asm is not design to do similar tricks. 
Main purpose of __asm is to create functional block in assembly language for speed.
On other hand #pragma aux is capable to do low level assembly construct and OW code generator optimization can improve overall code.
Anyway you can not expect any improvement related to __asm.
Also you can not use any relation between __asm and #pragma aux in-line assembly.
They are completely independent and code generator can put some code between last __asm and next #pragma aux in-line code.
It is possible to use consequence of #pragma aux in-line assembly code but CPU flags are not guarantie any way between two blocks because code generator don't preserve CPU flags.
If you want to process flags you must save it to some output register ((e)dx (e)ax). Look into tinyio.h in  bld/watcom/h directory how it can be done.

I recommend you to use #pragma aux in-line code for this because you have conrol over registers and CPU flags.

You can use macros in #pragma aux that you can define some code templates and fill in some specific data.
You must decide how flags will be handled if in assembly code or in C/C++ code.
any mixing is not possible.

**Comment by joncampbell123** [comment]
Would it be possible to add to "pragma aux" a way to say that the return value of the inline asm is a CPU flag or condition? I'm looking for a way to call a pragma aux asm function that makes a system call, and to specify the return value is CF (for example), and then, if the asm function is used in an if() statement, for the generated code to become a JC/JNC conditional branch.

It would be useful for example to write something in pragma aux that calls a DOS system call, and then signals the return value is the CF flag (the call would provide no other information).

In the DOSLIB case I am working on, I have no control over the APIs I'm calling. Many VxD calls use CF to signal an error and some use ZF to signal some conditions.

**Comment by joncampbell123** [comment]
The example above would become:

    #pragma aux Test_Sys_VM_Handle = \
        "int 20h" \
        "dw 0x0004" \
        "dw 0x0001" \
        parm [ebx] \
        value [zf]
    
    if (Test_Sys_VM_Handle(someHandle)) { /* ZF set, handle matches */
        /* do something because someHandle is system VM */
    }
    else {
        /* do something else */
    }

**Comment by jmalak** [comment]
OW code generator can not handle CPU flags, you must assign output register which is not used by VXD call and add instructions which fill this output register by flags by example simplest solution

extern unsigned char Test_Sys_VM_Handle( unsigned );
#pragma aux Test_Sys_VM_Handle = \
    "int 20h" \
    "dw 0x0004" \
    "dw 0x0001" \
    "lahf" \
    parm [ebx]  value [ah]

if (Test_Sys_VM_Handle(someHandle) & CPU_ZF ) { /* ZF set, handle matches */

**Comment by jmalak** [comment]
Anyway how you thing you can get info about CPU flags if any instruction can change CPU flag?
It is possible in pure assembly if you have full control over CPU but in C you have control over C statements and variables and not over CPU instructions. Code generator optimizer can reorganize instructions or replace one by others etc.
You have only control if you are in assembly block, but as soon as you are out of this block compiler has control over generated code and what will be there is complex process.

Potential solution could be to define function get_CPU_flags like this

extern unsigned get_CPU_flags( void );
#pragma aux get_CPU_flags = \
"pushf" "pop eax" value [eax]

and use it immediately after VXD call (this call must be #pragma aux in-line code, no __asm statement), there is big probability that code generator doesn't fill there anything, because eax register is generaly volatile for return value that no registers rearangement will be necessary.
Try to use it in real code for more issues and you will see.

**Comment by joncampbell123** [comment]
Ok

**Comment by joncampbell123** [comment]
Just an update: It turns out that GCC is a better fit for this kind of VxD programming than Open Watcom. GCC's inline __asm__ better supports the register-level input and output I need. GCC 6.1.x apparently added the ability to declare CPU flags as boolean outputs, which could be returned by static inline, which is then optimized down to a conditional branch, which is *exactly* what I was asking for here.

**Comment by jmalak** [comment]
I understand, but it is not supported by OW code generator.
Without OW code generator re-design it is not possible now.
