### ISSUE TITLE
Various C library test failures

### ISSUE THREAD

**Issue by pchapin** [open-watcom/open-watcom-v2#327]
I'm seeing the following failures in the C library tests (on SuSE Linux)

    ./chktest.exe /home/peter/Projects/OW/bld/clibtest/result.log
    line 9: '/home/peter/Projects/OW/bld/clibtest/regress/direct' test failed
    line 26: '/home/peter/Projects/OW/bld/clibtest/regress/heap' test failed
    line 37: '/home/peter/Projects/OW/bld/clibtest/regress/mbyte' test failed
    line 42: '/home/peter/Projects/OW/bld/clibtest/regress/misc' test failed
    line 44: '/home/peter/Projects/OW/bld/clibtest/regress/process' test failed
    line 55: '/home/peter/Projects/OW/bld/clibtest/regress/safembyt' test failed
    line 72: '/home/peter/Projects/OW/bld/clibtest/regress/startup' test failed
    line 80: '/home/peter/Projects/OW/bld/clibtest/regress/time' test failed

The nature of the errors seems to vary from failed assertions to what looks like an issue with the makefile to segmentation faults. Are these tests failing for others?

**Comment by jmalak** [comment]
It is failing because regression tests are "DOS" like oriented.
On DOS and NT OSes it is working without problem.
I can suppress failing tests on Linux, but it is for somebody who want improve CRTL on Linux or improve compatibility with POSIX.
- missing multi-byte support on Linux (multi-byte related tests are failing)
- direct tests are OW extensions oriented, they should be reworked for POSIX standard
- process related tests use functionality not available on Linux 
- etc.
On my box 32-bit OpenSuse I get
	C run-time libr. : Failed!
		bld/clibtest/regress/direct	direct
		bld/clibtest/regress/heap	heap
		bld/clibtest/regress/mbyte	mbyte
		bld/clibtest/regress/misc	misc
		bld/clibtest/regress/process	process
		bld/clibtest/regress/safeio	safeio
		bld/clibtest/regress/safembyt	safembyt
		bld/clibtest/regress/startup	startup
		bld/clibtest/regress/streamio	streamio
		bld/clibtest/regress/time	time

**Comment by pchapin** [comment]
Thanks @jmalak. It makes sense to me to leave the tests there (don't disable them for Linux) because they serve as a reminder that there is more work to do on that platform. I'll try to set up the build on my Windows 10 box at some point and see how things go there for me.

I will close this issue.
