### ISSUE TITLE
Broken CI?

### ISSUE THREAD

**Issue by bmanga** [open-watcom/open-watcom-v2#344]
I am currently getting some weird errors from Travis, which I think are unrelated to the code being run, but more likely to the recent changes to the yaml file.

**Comment by jmalak** [comment]
Yes, it is not related to code. 
It is due to I am reworking travis-ci build system to try include OSX build and use new features of Travis system (Build Stages) to overcome job time limit 50 minutes.

**Comment by jmalak** [comment]
I finished implementation of new Travis features.
Now build is divided to several jobs that it is possible add documentation build and partialy OSX build.
Current build of Documentation is accessible by Wiki https://github.com/open-watcom/open-watcom-v2/wiki/Open-Watcom-Documentation. I added some internal documentation too.
Now OW build should be OK again.

**Comment by bmanga** [comment]
Great job @jmalak ! I will start work on a new regression test suite soon, that we can hopefully integrate seamlessly as a build step. 
In the meantime,  could you have a look at why Travis still fails for #343? It still doesn't seem code related.

**Comment by jmalak** [comment]
It is fixed now. 
There was problem that external storage is used to pass data between jobs and access to external storage  uses credentials.
For pull request builds credentials are removed for security reason, because it is run by anybody and access to resources could be gained.
Therefore this external storage can not be used for pull request build.
I reworked scripts that for pull requests no external storage is used.
I will optimise OW build to build only minimal tools versions to be build as quick as possible (limit 50 minutes for one job).
Only regular build can be divided to several jobs that it will be possible to run test suites regularly, but for pull request it is not possible (all is one job with 50 minutes maximum).
