### ISSUE TITLE
Linker "PATH" and "FILE" directives issue.

### ISSUE THREAD

**Issue by beketata** [open-watcom/open-watcom-v2#359]
I'm using watcom in the Windows environment.

When I try to link the project with both directives as: **PATH debug FILE &ast;.obj** 
I got an Error! **E3033: directive error near ' FILE &ast;.o'**
But with **FILE debug/&ast;.obj** it compiles with no any errors.

Exactly the same issue with latest release and previous one.

**Comment by jmalak** [comment]
Thanks for your bug report.
It looks like WLINK command line parser bug, because both words "PATH" and "DEBUG" are directive keywords and parser think that PATH directive has no argument and is followed by DEBUG directive. 
I will fix it by rule that PATH must have at minimum one parameter if no {} braces are used.
as workaround you can use construct "...  PATH {debug} FILE ... ".

**Comment by beketata** [comment]
The kinds of words in the path directive does not matter.
I tried to change the directory name from "debug" to "ttt" for example - the same error.

**Comment by jmalak** [comment]
thanks for analysis.
does it work with {...}?

**Comment by beketata** [comment]
With **PATH {debug} FILE &ast;.obj** or **PATH {ttt} FILE &ast;.obj** the same error:
Error! E3033: directive error near '} FI'

**Comment by jmalak** [comment]
it is fixed by d2683a354e42e20ed9486e6170c3a63664fcfe5a commit
stupid mistake in PATH processing incorrect return value

**Comment by beketata** [comment]
Thank you!

**Comment by jmalak** [comment]
You are welcome
