### ISSUE TITLE
C/C++ Compiler. How to align certain data in memory?

### ISSUE THREAD

**Issue by beketata** [open-watcom/open-watcom-v2#367]
Like by directive __declspec( align( # ) ) for MS.

**Comment by jmalak** [comment]
OW compilers are using natural aligment., you cannot control memory alignment directly.
Usage of this directive on 16 and 32-bit architecture is problematic due to problem with stack alignment which is naturaly alligned to sizeof( int ). Introduction of this directive requires support from compiler/code generator and CRTL and introduce some undefined behaviour for such pointers.
