### ISSUE TITLE
pragma aux inline assembly with C macros

### ISSUE THREAD

**Issue by pgrAm** [open-watcom/open-watcom-v2#390]
Hi,

I use the inline assembler quite a bit, but I'm always irritated when I can't use any macros inside of it and as such end up with a bunch of confusing constants. for example:
```
#pragma aux vramCopyPage = \
"mov dx, 0x3c4"\ 
"mov ax, 0xff02"\
"out dx, ax"\
"mov dx, 0x3ce"\
"mov ax, 0x0008"\
"out dx, ax"\
"mov ax, 0xA000"\
"mov es, ax"\
"mov ds, ax"\
"mov cx, 19200"\
"cld"\
"rep movsb"\
"mov dx, 0x3cf"\
"mov ax, 0x00ff"\
"out dx, ax"\
 parm [di] [si]\
 modify exact [ax dx es ds cx di si];
```

It would be nicer if I could write things like mov ax, VGA_MEMORY_OFFSET. Is there currently a way to do this in OW? If not could such a feature be implemented?

**Comment by jmalak** [comment]
The problem is that data to in-line assembler (by pragma aux) is sent as string that instructions are not tokenized by C preprocessor but by assembler.
Symbolic constant are mostly defined as C macro that is not possible to replace it in string.
There is possible to use `__asm` directive for in-line assembly which is fully tokenized by C preprocessor.
But `__asm` directive can not be used in `#pragma aux` directive.
Pragma aux define instruction as series of bytes that you can use
`#pragma aux foo = b1 b2 b3 b4`
in this case bytes are fully processed by C preprocessor that you could use C constants.

**Comment by jmalak** [comment]
By example you can combine instructions and bytes in `#pragma aux`
This is legal
`#pragama aux foo = "inc ax" b1 b2 "dec bx" ....`
But it is your responsibility that included bytes give valid instruction.

**Comment by jmalak** [comment]
As workaround you can use
```
#define STR(...) #__VA_ARGS__
#define INSTR(...) STR(__VA_ARGS__)

#define CONST1  10

extern void foo( void );
#pragma aux foo = INSTR( mov ax, CONST1 )

```

**Comment by pgrAm** [comment]
Thanks for the workaround
