### ISSUE TITLE
in C _wfopen doesn't use demanded encoding UNICODE

### ISSUE THREAD

**Issue by vareille** [open-watcom/open-watcom-v2#403]
On windows x64 with open-watcom-2.0-2017-11-01, I do:

    wchar_t lBuff[1024];
    FILE * lIn = _wfopen(myFileName, L"rt, ccs=UNICODE");
    fgetws(lBuff, 1024, lIn);

it compiles and links, but at runtime
lBuff doesn't contains the UNICODE string
(it works fine with visual studio and mingwin gcc)

it seems that ccs=UNICODE is not taken into account.

**Comment by jmalak** [comment]
The problem is this function/feature is not standard, it is some kind of extension.
Generaly it is unportable code. 
OW run-time libraries doesn't support this extension to _wfopen even if support _wfopen function.
If it is widely used extension then we can implement it, but we need reference to original implementator to apply this extension compatible way.
Anyway I don't know what mean ccs=UNICODE.
It looks like setup of character set, but wide_character oriented funtion works with UNICODE characters by default that it looks like redundant.

**Comment by vareille** [comment]
The ccs=UNICODE (equivalent to ccs=UTF-16LE) opens the file as wchar_t text (instead of char text). which makes it easy to read and write. Without this microsoft extension (also implemented in gcc) to open a text file written in wchar_t you have to open the file as binary, read the BOM to determine it is UTF-16LE. and parse the bytes into a wchar_t pointer while detecting the end of the file as binary. Not impossible, but not as easy. I believe as you've implemented _wfopen which accept wchar_t parameters, it makes sense that this function could write/read wchar_t text files. At the moment, it can only write char text or binary files.

**Comment by alexeyneu** [comment]
not right.
https://github.com/alexeyneu/tool3/blob/4cfc5a51cf2fc139c5a84c0136162718c5dab40d/tool3/MainFrm.cpp#L109

**Comment by vareille** [comment]
your example doesn't pass the string  "r+,ccs=UNICODE" which is the one not taken into account.
