### ISSUE TITLE
Could somebody possibly create a Discord server for Open Watcom V2?

### ISSUE THREAD

**Issue by SeanRamey** [open-watcom/open-watcom-v2#462]
Well, the title pretty much says it all. Could somebody possibly create a Discord server for Open Watcom V2? [https://discordapp.com/open-source](url)

It would be nice to get Open Watcom V2 into the public a bit more. Discord is great for discussions on the project, and for finding help with stuff. This would be another great step to bring Open Watcom into the future.

**Comment by ArmstrongJ** [comment]
I've never used Discord before, and I'm doubtful I would personally use it just for this project.  I'm not saying it's a bad idea, but I'm just being honest. Perhaps some other devs here might...

Would it really help "get Open Watcom V2 into the public a bit more?"

**Comment by SeanRamey** [comment]
Why wouldn't it help? I feel that open watcom is a really great compiler, especially for retro development, which is what I use it for. And since it seems to be going in the direction of a modern compiler, then of course you would want more people to know about it, so they can use it! I think Discord would be helpful for discussing things though. I recently had a question about building Open Watcom on MacOS, and I couldn't find anywhere to properly ask the question and have a full discussion.

**Comment by jmalak** [comment]
We are small group with limited free time to spend for OpenWatcom.
For us is important automate all necessary task for building/testing OW.
If you want some new thing as Discord then you can contribute and setup it to work with OW.
It need some administration etc. and we don't waste our time to new service which is not necessary for OW build.
Anybody is welcome to help with OW and contribute any way.
Problem with MacOS is that we doesn't have any regular contributor for this OS.
Travis CI is able to build OW for MacOS, but it is not possible because it take more time then it is limit for each jobs. Therefore MacOS build on Travis CI is disabled now.

**Comment by SeanRamey** [comment]
Well, then I might just setup a Discord server myself. I just didn't think that I would be a very good person to do it, because I know very little about the Open Watcom v2 source and basically nothing about it's contributors.

So, how does it build it for MacOS? Can you list the steps for me somehow? I've mostly got it built, but I have problems with the dosbox utility that it needs, so I skipped that part, and the "executables" that I got out of it, seemingly, aren't compatible with MacOSX. Other than that, it was straightforward.

**Comment by jmalak** [comment]
You can ask for any information or help here.
I am not familiar with MacOS; I have only general knowledge about it.
If you have some problem with building on MacOS then you can put details here.
Please put here some details about DOSBOX problem or build log to be able help you.

**Comment by jmalak** [comment]
Anyway OW port to MacOS doesn't exist. 
It needs to port OW run-time libraries and some OW tools (Debugger/TRAP etc) to MacOS.
It only build OW on MacOS that you can use it on supported platforms.

**Comment by SeanRamey** [comment]
I'll post some information about my issue on here in a little while.

I'm not really familiar with MacOSX either. I only have to use it for my job, and I'm free to use the laptop for whatever at home as well, so I was going to try to get OpenWatcom built on it so that I can work on my DOS game with Mac or Windows. I've learned quite a lot about Mac in a short time though, and for the most part, it seems to be Linux compatible, (at least most command line programs), but apparently not completely. So I figured that if OpenWatcom could be compiled for linux, then it would work on MacOSX.

**Comment by jmalak** [comment]
If you are able run Linux application on MacOS then you can use OW for Linux on MacOS to build application for DOS, Windows, OS/2, Linux on MacOS in Linux mode.

**Comment by SeanRamey** [comment]
Ok, so I've made a discord server for Open Watcom V2. Here is the link: https://discord.gg/5WexPNn
I'll need some input from everybody on what the rules should be. Also, suggestions on what other channels there should be.

**Comment by jmalak** [comment]
What kind of information you need?

**Comment by SeanRamey** [comment]
I just want to know if there are specific rules that should be added to the discord server? Such as "no saying this, that, or the other thing.." or maybe "no discussions about this certain topic..." or whatever. Right now, it's pretty much just free and open, do as you will, within a small set of limits. Currently the rules are:
```
Rules:
1. No NSFW discussions.
2. Keep the discussion on topic per the respective channels, general "get to know each other" discussions are to take place in #general
```

Also, the current text chat channels are:
```
#general
#support
#feature-discussion
#bug-discussion
```
If anybody can think of better "categories" for discussion, or some to add to the list, then let me know.

If you're not familiar with Discord, try it out! Download it, make an account, and join the server! You guys that contribute regularly can use it to communicate with each other about problems you are having, ideas that you might wanna bounce off somebody else really fast, or just to get to know each other a bit better.

**Comment by jmalak** [comment]
For me it looks OK.
We don't need any discution restriction.

**Comment by d3x0r** [comment]
gitter has better integration with github (like tracking updates to issues/PR/commits).  Single click - login with github account even.
https://gitter.im
It even attempts to register a badge on README.md ... something like this... so from the project one click to the chat.

[![Join the chat at https://gitter.im/sack-vfs/Lobby](https://badges.gitter.im/sack-vfs/Lobby.svg)](https://gitter.im/sack-vfs/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Such things as discord/gitter aren't nessecarily for the project core to work on but can provide community support; three.js channel, for instance, rarely, if ever, gets comments from the core coordinators... others like for Gun DB the author is active, but there's a lot covered by community also.

**Comment by negge** [comment]
There is already a #watcom IRC channel on freenode.  Why not just use that for discussion instead of yet another proprietary chat product?

**Comment by jmalak** [comment]
Today I connected to this server and I was unpleasantly surprised by what can be done from the discussion server for Open Watcom V2. I'm sorry to say that, but this server is a site that has nothing to do with Open Watcom V2. It is the mouthpiece of several individuals who have never done anything for OW v2, but will only explain to you how bad OW v2 is.
I don't thing Open Watcom V2 is perfect, but why server which should be created for Open Watcom V2 should denigrate Open Watcom V2.

Please @SeanRamey remove any reference to Open Watcom V2 from the name of this server etc. or remove it, I don't want to have anything with such server which don't do anything useful for Open Watcom V2.
You can rename it to Open Watcom 1.9 if you wan't but I don't want any relation of this server to Open Watcom V2.
I will remove all references to this server from Open Watcom V2 because it has nothing common with Open Watcom V2.

**Comment by pchapin** [comment]
I'm fairly new to Discord, although I am a member of a couple of other Discord groups. My very limited experience (one night) with this Discord server was fine. I had a short, but appropriate conversation in the #general channel. It probably does make sense to remove the "V2" in the name since some of the discussion appears to be about Watcom versions other than V2.

**Comment by jmalak** [comment]
Now it is important @SeanRamey must remove the reference to Open Watcom V2, that we don't confuse users.
Probably @SeanRamey could transfer owner rights for original Discord server to somebody who is active on this server to be maintained by somebody from server community.
We have new Discord server with appropriate rules and I will try to monitor it constantly now and later one per day/week what happen there to not have the same problems as on old server, I think it was big mistake to un-manage it.
But it is hard to do all things, no time.
