### ISSUE TITLE
Docker Build Image

### ISSUE THREAD

**Issue by crempp** [open-watcom/open-watcom-v2#471]
I absolutely love this project and am so appreciative of all the work that has gone into it. I hope my minor contribution can help others.

The largest problem I've had with Open Watcom is setting up the build environment, especially on a Mac. Once it's setup it's great. For this reason I thought it may be helpful to have a Docker build image. Not only will this make it incredibly easy to get started using Watcom but also it makes it possible/simple to use CI build tools like CircleCI or Jenkins.

Here's my initial stab at a Docker build image. It functions for my particular use case but I know I'm missing things and there's more work to do. I hope others will try it out, let me know what doesn't work and perhaps contribute.

https://hub.docker.com/r/lapinlabs/watcom/

**Comment by jmalak** [comment]
Hi, Thanks for your info.
The main problem with CI is that jobs are limited by run time, probably the same problem with sinilar sites.
On CI is possible to run build also for MAC, but it is always stopped due to maximum run time is overflow that I stopped it already.
To fix this issue build is divided to several jobs to not overflow maximum run time per job and use CI cache to store intermediate things to be available for each serialized job.
Build requires several jobs serialized:
initialization phase (extra job) - prepare GITHub repository
bootstrap phase (extra job)
build phase (extra job per executables + extra job for documentation)
test phase (extra job for each test (C compiler, C++ compiler, F77 compiler, Assembler, C run-time )
finalization phase (extra job) - update GITHub repository

If you have some trouble then you can try to ask. If I know than I will help you.

**Comment by crempp** [comment]
@jmalak I may not have explained this clearly.

This is Docker image is not to build Open Watcom itself. It's meant to be used for end users like myself to build my own project **using** Open Watcom.

For example. I'm writing a 16 bit OS and using Open Watcom v2 to compile. Rather than have to setup the Open Watcom environment on my local machine I can use this image. Here's a simple example. I use Scons but you can swap out for `make` pretty easily.

In my OS project I add a file `Dockerfile` containing
```
FROM lapinlabs/watcom

RUN apk add --no-cache --update scons

WORKDIR /app

CMD ["scons"]
```

Then I can build my project by 

1. Build the image (only need to do this once)
```
$ docker build -t my-builder .
```
2. Run 
```
$ docker run --rm -v `pwd`:/app my-builder
```

By doing this I can build my project by running that second command. I never had to setup Open Watcom on my local machine.
