### ISSUE TITLE
Wrong relative include paths

### ISSUE THREAD

**Issue by mittorn** [open-watcom/open-watcom-v2#578]
When compiling source file with relative include, owcc searches it not relative source file path, but relative to the current directory. It this correct? Current dir has high priority, so it cannot be overriden by include flags and i cannot find way to workaround it without changing cwd

**Comment by jmalak** [comment]
I understand the problem, but it is by design complex logic with some path caching.
Yes, it is working relative to current directory and to any directory which was used.

I added extra options to change this logic a little bit.
There are following options which change include path behaviour.
-x     ignore any INCLUDE environment variables
-xx   ignore any standard include directories as` . `(current directory), `../c` , `../h` etc.
Try to use -xx option and specify your source directory by -I option.
It could help you.
The logic is complex and can use multiple drives on DOS-like filesystems that current working directory is defined for each drive.
If you specify  required behaviour then we could add some option which replace current directory by source file directory in the search logic. But take into account there is different parts of search list with different priority.
If you are interested in this logic then code is in function `doOpenSrcFile` in `bld/cc/c/cmain.c` source file for C compiler and in function `doIoSuppOpenSrc` in `bld/plusplus/c/iosupp.c` for C++ compiler and in `PP_IncludePathFind` in `bld/cpp/c/preproc.c` fro C preprocessor.

**Comment by jmalak** [comment]
OW build system uses -x -xx options by default to have well defined behaviour for include path searching.
Default logic is to traverse all "defined" and all "efectively used" path that search is done relative to each existing path in the ring which is automaticaly extended by any used include file path.
It is necessary for backward compatibility to hold this behaviour that any change can be add by new option only.

**Comment by mittorn** [comment]
-Wc,-xx option helps, added it io owcc waf plugin. Maybe it should be default in owcc? What owcc driver is?

**Comment by jmalak** [comment]
owcc driver transform gcc like options to OW tools options (C and C++ compilers, WASM assembler, librarian and linker). something like gcc/g++ or Microsoft cl command. OW has its own driver wcl386 wcl which do similar thing bud use OW natve options. OW has Microsoft cl driver clone for compatibility with MS cl, it translate MS cl options to OW tools options.

OW project respect backward compatibility, that new version should work as replacement for older version.  Sometime it is not possible, but tool options are compatible.
-xx option is new for OW 2.0. It doesn't exists in previous versions, therefore we can change this option behaviour if we need without problem. But owcc tools was adde a few versions before.

**Comment by jmalak** [comment]
if you want add some option permanently to command line then you can use WCC386/WCC or WPP386/WPP environment variable to add permanent option, these environment variables are processed before command line.
