### ISSUE TITLE
CLI is not compatible with the CommandLineToArgvW function

### ISSUE THREAD

**Issue by ABBAPOH** [open-watcom/open-watcom-v2#629]
Hello, we are trying to add support for the OpenWatcom toolchain in Qbs [0] and we've encountered a problem.
It appears, that command-line interface of the compiler is not compatible with the CommandLineToArgvW function [1], namely the section about escaping quotation marks.
Consider the following example:

wcc.exe "-dDEFINE=\\"foo bar\\"" main.c

I expect this to define a macro named DEFINE with the value "foo bar". Unfortunately, this doesn't work.
This, however, works:
wcc.exe -dDEFINE="foo bar" main.c

Unfortunately, this means we have to implement custom escaping rules for the Open Watcom compiler which doesn't seem like the right way to do (for instance, what are those rules?).

[0] https://codereview.qt-project.org/c/qbs/qbs/+/313375
[1] https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw

**Comment by jmalak** [comment]
The problem is that OW C compiler has old hand-crafted command line processing parser.
There is no strict rules in command line processing.
It is processed as long string and each option eat appropriate part of this string, each option can use different terminators etc.

OW generall rule is backward compatibility it include command line processing that it is hard sometime integrate new feature to it.
Users have a lot of makefiles etc. that some incompatible change break it.

One of this new feature "extended -D macro definition" was integrated this way. The quoting is a problem with C compiler at all.
I will review macro definition processing code if there is some possibility to use option quoting this way or not.

**Comment by jmalak** [comment]
did you test it for OW C++ compiler?
This compiler use tool generated command line parser with well defined behavior.

**Comment by ABBAPOH** [comment]
No, same error. It might help that compiler treats "-Dfoo" as a file name and complains about the missing file.

**Comment by jmalak** [comment]
I dont thing that quoting over option is correct. In this case if it is exec it is not option but string and what it means is on compiler.
If it is processed by shell then it is unquoted and to compiler is passed option. If you pass it by exec as command line it cannot work any way because it is string not option again.
How you call compiler exactly? By shell by WinExec or by other method?

**Comment by denis-shienkov** [comment]
With '-d+' option we got another error:

```
wcc.exe "-d+DEFINE=\"foo bar\"" main.c
...
Error! E1139: Command line contains more than one file to compile
main.c: 11 lines, included 797, 0 warnings, 1 errors
```

But, seems, it does work with the OW 'gcc' syntax wrapper:
`
owcc.exe "-DDEFINE=\"foo bar\"" main.c`

Maybe is it an option for us?

**Comment by jmalak** [comment]
Try to read C/C++ user guide for -d and -d+.
Any C or C++ doesn't specify -d option syntax
I think only POSIX specify how basic -d for cc should works
Any other forms are compilers extension to POSIX or compiler specific anyway
OW use I think syntax similar to gcc but not exactly same.
Therefore syntax of C/C++ compilers is well defined.
It is on to you correctly pass your selected options to OW compiler from your environment and for selected type of execution.
It has nothing to do with CommandLineToArgvW function, you must use this function proper way to pass arguments in expected form for compiler.
If it doesn't work as you expected try to debug to get full command line passed to compiler or array of all arguments and check values to see what is wrong.

**Comment by jmalak** [comment]
to owcc it works because you use correct syntax.
You expect something without reading basic compiler user guide and report it as bug.
It is not good approach.

**Comment by jmalak** [comment]
owcc is not gcc replacement, it is for POSIX like environment

**Comment by denis-shienkov** [comment]
> It is not good approach.

I'm sorry, but, what's the right approach using the wccXYZ/wppXYZ compilers? The '-d' option did not work, the '-d+' option did not work too.

**Comment by jmalak** [comment]
How we can build anything by OW?

**Comment by ABBAPOH** [comment]
> You expect something without reading basic compiler user guide and report it as bug.

I am not saying this is a bug, but merely a suggestion - this is how most Windows programs behave these days (AFAIK, compiler generates the call to CommandLineToArgvW before passing arguments to main(int argc, char *argv[]). I do also understand that wcc is a DOS-like program with promises for backward-compatility.

But let us investigate if we can use the POSIX wrapper, if all goes well, there's no need to change wcc/wpp at all and I will close the issue. I suppose there is no big difference between owcc/wcc in terms of features?
There's also always an option to disable quoting before passing arguments to the process - we will investigate that too.

Thanks for participating in the discussion, anyway.

**Comment by denis-shienkov** [comment]
> owcc

One question: is this 'owcc' wrapper available only on the OWv2, or it is available and on the 'native' old OW?

**Comment by jmalak** [comment]
OW is not specialized Window platform tools. 
Windows platform is one of many.
That most of thing are done without nowdays-Microsoft technology to works on other Windows platforms and generaly on non-Windows platforms.
OW now incline more to POSIX, because it is one of well defined long-term standard.
All 32-bit tools are working on all Windows platform as NT 4.0 and above and Windows 9x etc. upto latest version dueto use of WIN32 API only.
We don't use any Microsoft components as redistribution etc. Until you build for 64-bit Windows host then Visual studio is used with full Microsoft dependency and related problems.
Command line syntax is well defined in documentation that if you use it as described in user guide then it works.
This syntax is working on all supported platforms. It can not use anything specific for one platform.
You can not expect that this syntax will be changed, it can be only for new options which are new in current development version. As soon as new release is done then new option is fixed and change is possible if some bugs is there.
There is zero chance to do such changes in OW or it must be change for very good reason.
owcc tools is relatively new and still in development. But it is used more and more that changes in interface must be done careffuly. But this tool is relative frequently changed.
There is no problem with introducing missing features following appropriate POSIX standard because it is relatively new tool.

Relation to OW 1.9 is standard all things working on OW 1.9 must work same way on OW 2.0.
But what is working on 2.0 not necessarily work on OW 1.9.
If you want develop for OW then you should develop on OW 1.9 and it should works with OW 2.0.
OW 2.0 is not official release it is clone of OW 1.9 which is ported to 64-bit Linux and Windows hosts by using native compilers.
OW 2.0 code is more portable to be biddable on more POSIX platforms. OW is biddable also on OSX.
There is one special port for arm architecture to run on Rapsbery-PI, it is created by gcc bootstrap compiler and is used for some DOS development or something similar.
OW 2.0 represent port to 64-bit hosts, bug fixes, some improvement of functionality etc. 
Unfortunately also more bugs then in OW 1.9 dueto big code base changes.

Anyway owcc is POSIX cc driver and OW 2.0 version has significant improvement, better LFN support, better slash\backslash support that it can work on DOS and other OSes with identical POSIX syntax. owcc do translation of path and filenames for host system. OW 2.0 version has also improved support for various architectures as 16/32-bit Intel. It also support OW Fortran compiler. OW 1.9 version has a few bugs which is fixed in owcc 2.0. The problem with owcc 1.9 can break you usage for various reasons. What is good that owcc 2.0 can work with OW 1.9 as replacement of old owcc.
But take into account that OW 2.0 is still in beta. OW 1.9 is last official version available and I think no other version will be released. Development of OW 1.9 is dead.

**Comment by jmalak** [comment]
OW is working on DOS, OS/2, 16/32/64-bit Windows, RDOS, Linux 32/64-bit, QNX (but not build-able due to original WATCOM use proprietary QNX Shared library. It is capable develop Netware NLM.

**Comment by jmalak** [comment]
Unforunately you can create your own OW tools driver specialised for your use with appropriate interface which you need.
It is not too hard.

**Comment by jmalak** [comment]
Anyway all toos for Windows use single/multibyte version of WIN32 API. It doesn't use Wide Version of WIN32 API.
It expect ANSI command line.

**Comment by jmalak** [comment]
if you are interested in Windows only then most of main tools are compiled as DLL and have exe driver.
This DLL interface is well described that you can use OW tools more efficient way by direct call of compiler from DLL.
But the interface is only single/multibyte not Wide version.

**Comment by jmalak** [comment]
I don't know anything about QBS and Qt and how it call Executable on each supported platform.
What is supported platforms for QBS?

**Comment by ABBAPOH** [comment]
QBS works on all major platforms, i.e. on Widows, Linux and Mac.
Under the hood, it uses the Qt library and invokes compilers and linkers directly using the QProcess class [0]. QProcess on Windows uses the CreateProcess winapi function [1]. When creating the command, QProcess escapes the arguments according to the rules used by CommandLineToArgvW (given the fact that most programs use it to parse CLI these days), here's the escaping code [2]. AFAIK on Linux/Mac no escaping happens as the spawned process accepts argc/argv exactly as passed to the exec function - there is no step when all arguments are merged into a huge string and then split back - they are passed as an array of strings.
It is possible to bypass the escaping code by using the setNativeAgruments() function in QProcess [3]. This requires changing Qbs code a bit, but it might work - we have the full control of the arguments passed to the compiler. @denis-shienkov is currently investigating if it actually works. Give us some time to investigate.
Thanks for the idea with a wrapper binary though - generally, this is not very performance-wise (we try to avoid spawning additional processes in Qbs as much as possible), but could be a last resort if anything else won't work.

[0] https://doc.qt.io/qt-5/qprocess.html
[1] https://code.woboq.org/qt5/qtbase/src/corelib/io/qprocess_win.cpp.html#488
[2] https://code.woboq.org/qt5/qtbase/src/corelib/io/qprocess_win.cpp.html#398
[3] https://doc.qt.io/qt-5/qprocess.html#setNativeArguments

**Comment by jmalak** [comment]
OK, I have a better overall picture now.
Any escaping signal to call shell and next execute escaped command in shell, probably for sanity.
If it will be directly executed then escaping is useless. But it depends on Qt layer.
I will wait for your investigation.

**Comment by denis-shienkov** [comment]
> I will wait for your investigation, no problem.

Yes, we can modify the QBS sources to pass the 'native' (non-escaped) argumrnts to the QProcess.. And, it does work, thanks for your time. :)

**Comment by jmalak** [comment]
You are welcome.
If any problem or something unclear in documentation with some option simply then open issue with relevant subject here.

**Comment by ABBAPOH** [comment]
Once again, thanks for your time!

**Comment by denis-shienkov** [comment]
UPD: I hoped now on OWCC driver. But, seems we can't use the OWCC driver due to these issues:

* https://github.com/open-watcom/open-watcom-v2/issues/707
* https://github.com/open-watcom/open-watcom-v2/issues/712
