### ISSUE TITLE
build error on FreeBSD 12.2

### ISSUE THREAD

**Issue by yamori813** [open-watcom/open-watcom-v2#664]
Hi

I try to build on FreeBSD/i386 12.2R. I have build error.

If you have advice, please let me know.

Thanks.

======== 13:21:40 /usr/home/hiroki/ow/open-watcom-v2/bld/browser/nt386 ========
/usr/home/hiroki/ow/open-watcom-v2/build/mif/wgmlcmd.mif(82): Error(E33): Unsupported building platform !!!!!!
Error(E02): Make execution terminated
Error(E42): Last command making (/usr/home/hiroki/ow/open-watcom-v2/docs/nt/wbrw.gh) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed

**Comment by jmalak** [comment]
The problem is simple, exactly what message saying
Please read basic [Wiki pages](https://github.com/open-watcom/open-watcom-v2/wiki/Build) about setup of build OW and read instruction in setvars.sh file.
You need to install DOSBOX and configure OW build script.
Anyway OW is not ported to FreeBSD that you can compile OW on FreeBSD for all supported hosts, but you can not use it as native FreeBSD application.
We support Linux host only.

**Comment by yamori813** [comment]
Thanks for your information.

I install dosbox on my FreeBSD host then build is complete.
