### ISSUE TITLE
Unable to run installer in DOS

### ISSUE THREAD

**Issue by robdaemon** [open-watcom/open-watcom-v2#710]
Using the 2021-06-20 01:52:19 build of `open-watcom-2_0-c-dos.exe`, I get an error trying to run the installer in MS-DOS 6.22:

```
Error: could not open message resource file (D:\OW20DOS.EXE)
```

note: I renamed the file to OW20DOS.EXE so it would fit in an 8.3 filesystem.

**Comment by jmalak** [comment]
thanks you for your bug report.
I will fix it ASAP.

**Comment by jmalak** [comment]
Sorry for delay, but the problem was with a few bugs in DOS LFN support.
It has problem if it is working on native DOS.
Now it should works as expected.
I tested it on box with MSDOS 6.22 and installer do all installation activities without problem.
Please check with new Installer build which will be created this night that it will be available tomorrow morning about 02:10 UTC.

**Comment by robdaemon** [comment]
Works now! Thank you!
