### ISSUE TITLE
owcc: does not link application with enabled exception handling option on Windows

### ISSUE THREAD

**Issue by denis-shienkov** [open-watcom/open-watcom-v2#712]
Hi all,

If we have one `app.c` file with empty main function:
```
int main() { return 0; }
```
and also have second `empty.cpp` file with empty content.

Then, when we compile it using the C/C++ flags `-x{c|c++}` and the enable exception flag `-feh` in this way:
```
$ owcc -xc -c app.c
$ owcc -xc++ -feh -c empty.cpp
$ owcc app.obj empty.obj
``` 
then linking faile with this error:
```
Error! E2028: __compiled_under_NT is an undefined reference
Error: Linker returned a bad status
```

PS: Other compilers does work with similar compilation sequence.

**Comment by jmalak** [comment]
Cross compile guide for begginers is [here](https://wiki.archlinux.org/title/Open_Watcom)

**Comment by denis-shienkov** [comment]
@jmalak , did you read my description? 

* If you omit the `-feh` flag, then all be fine.
* If you will change the compile order as:
```
$ owcc -xc++ -feh -c app.c
$ owcc -xc -c empty.cpp
$ owcc app.obj empty.obj
```
all be fine.

It is a bug in compiler, because other compilers does works with enabled "exception support" flags

**Comment by jmalak** [comment]
It is not a bug but it is absolutely useless usage for nonsense.
This case is not handled by OW, because combine blank module with some one line as main is useless.
As soon as you will have some real code all will be OK.
The same problem if you use main module without any code you get a message.
The __compiled_under_NT symbol is used for checking that all linked modules were compiled with same setup.
Because there is no C++ code this symbol is not find due to missing C++ run-time stuff.
I can add symbol to link blank module with C++ run-time stuff that you don't get the message.
But no gain for real C++ code because your case is nonsense.

**Comment by denis-shienkov** [comment]
> But no gain for real C++ code because your case is nonsense.

@jmalak , no, it is your sentence is a nonsence, please re-open this bug.

Even if I add any code to the `empty.cpp` file, then I got the same error. The problem not is in that the `empty.cpp` module is empty, the problem is in `-feh` option or something else (an empty file was just for simplification).

PS: We already have an auto-tests with the similar use cases for a lot of compilers (GCC, MinGW, Clang, MSVC amd so on). There this (similar) link sequence does work there. 

Do you understand, that you tell nonsense? Or do you think that you smarter that other peoples who wrote the auto-tests? :))
