### ISSUE TITLE
`owsetenv.sh` adds `binl` folder to path, as supposed to `binl64` in `open-watcom-2_0-c-linux-x64`

### ISSUE THREAD

**Issue by volkertb** [open-watcom/open-watcom-v2#744]
In 64-bit Linux, assuming that Open Watcom v2 was installed in the default directory `/opt/watcom`, the environment script `owsetenv.sh` adds `/opt/watcom/binl` to the PATH, as opposed to `/opt/watcom/binl64`, even in the 64-bit Linux version (`open-watcom-2_0-c-linux-x64`). This still works, but it seems suboptimal. Why not use the 64-bit executables instead of the 32-bit ones?

The toolchain appears to work fine when I modify this directory in the script file to the `binl64` variant manually and then `source` it.

I assume this was an oversight, and simple to fix? Or was this done deliberately?

**Comment by jmalak** [comment]
It is due to OW debugger and other tools are not ready for 64-bit host. It requires loadable modules to be 64-bit. Now not all are ready.
I will try to modify installer scripts to exclude some 64-bit tools and then on the PATH will be both .../binl64:.../binl: to run debugger and other tools from 32-bit directory and rest of tools from 64-bit directory.

**Comment by jmalak** [comment]
it is now fixed, any installer contains all hosts and if you install 64-bit version then  in `owsetenv.sh` is both path in right order `.../binl64:.../binl:...` and it install all 64-bit objects except debugger
