### ISSUE TITLE
Incompatibility between va_list and FormatMessage

### ISSUE THREAD

**Issue by ccawley2011** [open-watcom/open-watcom-v2#745]
The following code compiles and runs correctly on Windows with both MinGW32 and MSVC 2019:
```
#define UNICODE 1
#define _UNICODE 1

#include <windows.h>
#include <stdio.h>
#include <tchar.h>

LPTSTR GetFormattedMessageV(LPCTSTR pMessage, va_list args) {
	LPTSTR pBuffer = NULL;
	FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_STRING, pMessage, 0, 0, (LPTSTR)&pBuffer, 0, &args);
	return pBuffer;
}

LPTSTR GetFormattedMessage(LPCTSTR pMessage, ...) {
	LPTSTR pBuffer;
	va_list args;

	va_start(args, pMessage);
	pBuffer = GetFormattedMessageV(pMessage, args);
	va_end(args);

	return pBuffer;
}

int main(int argc, char *argv[]) {
	LPTSTR pBuffer;

	pBuffer = GetFormattedMessage(TEXT("%1: %2 %1\n"), TEXT("Test message"), TEXT("This is a"));
	if (!pBuffer) {
		_fputts(TEXT("GetFormattedMessage() failed\n"), stdout);
		return EXIT_FAILURE;
	}

	_fputts(pBuffer, stdout);
	LocalFree(pBuffer);

	return EXIT_SUCCESS;
}
```

With Open Watcom however, `va_list` has a different definition on Windows compared to other compilers, which causes compilation to fail with the following error:

```
test.c(10): Error! E1071: Type of parameter 7 does not agree with previous definition
test.c(10): Note! N2003: source conversion type is 'char **'
test.c(10): Note! N2004: target conversion type is 'char *(*)[1]'
test.c(10): Note! N2002: 'FormatMessageW' defined in: D:\OpenWatcom\h\nt\winbase.h(2148)
```

Replacing `&args` with `args` fixes compilation with Open Watcom, but breaks other compilers.

**Comment by jmalak** [comment]
It is not compiler problem with va_list or compiler, but language standard which is used by compiler.
By default OW use C89/C90 standard. C99 standard is not fully supported, but most of features are available.
You need to use -za99 option to use C99 standard.

**Comment by ccawley2011** [comment]
I've opened PR #746 with a fix for this.

> You need to use -za99 option to use C99 standard.

That doesn't seem to make a difference.

**Comment by jmalak** [comment]
You are right, the prototype is not correct. 
It is interesting that it caused a internal problem in OW and this problem was not fixed on Intel architecture.
Maybe it is some historical issue before first standard C89.
No problem with ALPHA, PPC or MIPS. 
I checked use of it in OW code base and there are some internal conditonal code to fix this issue for Intel architecture on some places.
Thanks for fix but I incline to fix the source of problem and don't mask it. Probably best solution is to define 
typedef char *__va_list;;
for Intel platform.
