### ISSUE TITLE
Linking compiled resources in the same way as normal objects

### ISSUE THREAD

**Issue by ccawley2011** [open-watcom/open-watcom-v2#748]
Both MSVC and MinGW allow linking compiled resources in the same way as normal objects. OpenWatcom doesn't have an equivalent to this, and requires a separate command to attach the resources to the final executable, which complicates integration with tools like CMake. 

Related CMake PR: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6637

**Comment by jmalak** [comment]
processing of resource file has its own rules and also various type of objects included and executable formats on different platforms (OS/2, 16-bit Windows, NT) that it has no sense to do such thing, because PE format to which it is specific solution doesn't solve problems any way for other platforms. Linker has appropriate directives to include resource files into executable during linking.
