### ISSUE TITLE
Spurious warning in C++ compiler (?)

### ISSUE THREAD

**Issue by amindlost** [open-watcom/open-watcom-v2#779]
When compiling the following fragment with the C++ compiler and all warnings enabled (via -wx):

```
void test(void)
  {
  char d[1024], p[1024], c;
  c = 0;
  d[0] = c;
  p[0] = c;
  }
```

it generates the warnings:

```
Warning! W836: col(26) symbol has different type than previous symbol in same declaration
Note! N837: col(26) companion definition is 'd'
Note! N392: col(8) definition: 'char d[1024]' in 'int main( int, char * * )'
```

Splitting the definitions to individual lines stops the compiler from complaining.

This does not occur with the C compiler, only the C++ compiler, and was tested on a locally built copy of the compiler from November 23.

(I'm a bit rusty, trying to get back into programming, but I'm fairly certain it shouldn't be doing this, though I could be wrong)

**Comment by jmalak** [comment]
Thanks for your bug report.
This bug is old one, the same behavior for OW 1.9.

**Comment by amindlost** [comment]
Thanks Jiri. Didn't know it had been around so long.

**Comment by jmalak** [comment]
In source code is following comment for checking for shared type
            // (1) make sure there were decl-specs
            // (2) typedef int I, *PI; is common
And in documentation it is commented as warning for potential programmer mistake

This warning indicates that two symbols in the same declaration have different types.  This may be intended but it is often due to a misunderstanding of the C++ declaration syntax.

Example:

     // change to:
     //   char *p;
     //   char q;
     // or:
     //   char *p, *q;
     char* p, q;

I will exclude array from such test that following will not raise warning message

     //   char *p, *q[3];
     //   char c, d[3];
     //   int   a, b[3];

**Comment by jmalak** [comment]
The arrays declaration is skip to get base type for comparison

**Comment by amindlost** [comment]
Thank you again, @jmalak.
