### ISSUE TITLE
"Size of Stack Reserve" and "Size of Stack Commit" not filled?

### ISSUE THREAD

**Issue by danielmarschall** [open-watcom/open-watcom-v2#780]
Hello,

I am building a DLL using OpenWatcom 2 and compared the output files with the files built with MSVC++ and MingW. I noticed that OpenWatcom does not set the PE fields "Size of Stack Reserve" and "Size of Stack Commit". Manually setting "op st" doesn't help either. Is this a bug?

Here is the comparison:

MSVC++ 32 bit
	Size of Stack Reserve         	00100000h
	Size of Stack Commit          	00001000h
	Size of Heap Reserve          	00100000h
	Size of Heap Commit           	00001000h

MingW32
	Size of Stack Reserve         	00200000h
	Size of Stack Commit          	00001000h
	Size of Heap Reserve          	00100000h
	Size of Heap Commit           	00001000h

OpenWatcom
	Size of Stack Reserve         	00000000h
	Size of Stack Commit          	00000000h
	Size of Heap Reserve          	00002000h
	Size of Heap Commit           	00001000h

Also, is there a way to increase the heap values? I'm afraid that my DLL might not work on some systems, because it usually need a lot of memory.

**Comment by jmalak** [comment]
DLL uses executable (application) stack.
If DLL need own stack then must be handled by user code and has nothing to do with these parameters.
I don't think if both fields has sense for DLL.
Bellow is one of valuable link [when it is commented](https://community.intel.com/t5/Intel-Fortran-Compiler/Stack-reserve-size-in-DLL-vs-EXE/td-p/1077326).
On the internet is many discussion about DLL stack size, but it is nonsense and totally confusing for users.
If you get "insufficient stack size" in DLL then you must correct stack size on main executable which allocate stack from OS because DLL code use stack space of main executable. For new thread in multi-threaded application is allocated new stack by OS based on values from main executable header.
Doesn't Mather what other tools fillin for DLL. Probably they use some common default value same as for executable because these values are irrelevant.

I thing heap size should be setup by linker to default value that you should be able to change it.
If not then report it and I will check why not.

**Comment by danielmarschall** [comment]
Thank you for your fast reply.

Linker option `OPTION HEAPSIZE=1m` indeed sets the value of "Size of Heap Reserve" to 00100000h.

Linker option `OPTION STACK=1m` gets ignored.

I do understand that DLL files don't have a stack, since the stack comes from the EXE file.

But I wonder why is "heapsize" accepted by the linker but "stack" not? In my opinion, it would be more consistent to either set **both** to zero or **none** to zero. Why just zero "stack" but not "heap"?

Personally, I would prefer that "stack" is written like it is an EXE file.

Reasons:
1. Every linker does it. There might be another reason behind it?
2. There *might* be some undocumented OS quirks that somehow evaluate the stack information of the DLL? Maybe things like RunDLL etc.?
3. It might be unnecessary, but it doesn't hurt if it is existing.

**Comment by jmalak** [comment]
I am not much familiar with Windows DLL loader because it is not described by Microsoft.
I red a few articles about process loading steps and it looks like the heap size fields in PE header are not be used for DLL too.
Heap size is global for application when process is created and for DLL is used Application heap or you must handle your own heaps by their explicit definition. What is in PE header is application default heap size and DLL has not defined anything like heap by PE header. 
There is no reason to follow behavior of other suppliers especially if it is not documented anywhere.
What should be there? 
What means these parameters if they are not used by DLL loader and are not documented anywhere?
What rules?
Nobody reported problem with DLL created by OW.
What you thing RunDLL is, how you can run DLL?

**Comment by jmalak** [comment]
OW use similar technology as RunDLL.
We have executable driver which load DLL and pass command line to DLL OW entry function.
You can call tool as simple executable from command line.
From application you load DLL and call entry function as many time as you want without penalty to start new process for each run.

**Comment by jmalak** [comment]
You only say what you want, but you give no real reason.
