### ISSUE TITLE
GetOpenFilename crashes in Win9x

### ISSUE THREAD

**Issue by musa96** [open-watcom/open-watcom-v2#844]
I'm using the March update of OpenWatcom 2.0, and when an application uses GetOpenFilenName or GetSaveFileName in Windows 9x, the application crashes with this: 
![Screenshot from 2022-03-24 11-04-40](https://user-images.githubusercontent.com/13893819/159870451-5b06f3d5-ccb2-403d-b339-13be8b1941aa.png)

This happens with the sample EDIT application included with OpenWatcom.

**Comment by MarekKnapek** [comment]
The same (similar?) problem occur for me, but with Microsoft Visual C++ Version 2.0 on Windows 98. The problem is running an application which uses GetOpenFileName WinAPI function under debugger. The under debugger part is important. When I launch my application without debugger attached, it works correctly. Also, compiling and running my application with Visual C++ 4.2 works fine, even with debugger attached. Might be Windows bug.

**Comment by jmalak** [comment]
I am not sure, but it could be GetOpenFileName API which could use specific handling for Windows 9x. It should be handled on run-time by Windows OS version, may be existing handling in debugger (for Windows 9x) is wrong.

**Comment by musa96** [comment]
The debugger is showing that is calling PrintDlg for some reason.

**Comment by jmalak** [comment]
The OPENFILENAME structure has different size in dependency on Windows version.
what _WIN32_WINNT you use?

**Comment by MarekKnapek** [comment]
I'm not the OP, I could reproduce this with MSVC 2.0 but could not reproduce this with MSVC 4.2 in both cases the `sizeof(OPENFILENAME)` is 76. I think, this is Windows or debugger bug that MSVC people also encountered and fixed / workarounded in newer version. I can not reproduce this with Open Watcom IDE 1.9 where `sizeof(OPENFILENAME)` is also 76.

**Comment by musa96** [comment]
> The OPENFILENAME structure has different size in dependency on Windows version. what value of _WIN32_WINNT you use?

I'm not really sure I didn't redefine that.

**Comment by jmalak** [comment]
If you don't specify version then it is minimum supported version 0x400.
It is Windows NT 4.0 and Windows 95 compatible.

**Comment by musa96** [comment]
I used the debugger and the sizeof(OPENFILENAME) is 76.

**Comment by joncampbell123** [comment]
Just from personal past experience with the Win32 API... do you zero the struct before filling it in and passing it to the API?

Just because you declare the struct doesn't mean the memory backing it is all zero, especially if declared on the stack.

There's lots of optional fields there that if nonzero trigger Windows to do additional things you might not expect.

**Comment by jmalak** [comment]
Next potential problem could be with _WIN32_WINNT value.
Windows 95/98 should use 0x400 (it is OW default), but if you change it then OPENFILENAME structure have incorrect size.
There is possible to use OPENFILENAME_NT4 structure which is compatible with Windows 95/98 instead of OPENFILENAME structure.

**Comment by joncampbell123** [comment]
> Next potential problem could be with _WIN32_WINNT value. Windows 95/98 should use 0x400 (it is OW default), but if you change it then OPENFILENAME structure have incorrect size. There is possible to use OPENFILENAME_NT4 structure which is compatible with Windows 95/98 instead of OPENFILENAME structure.

Yes, but OPENFILENAME has the lStructSize member which is supposed to tell Windows how big your struct size is so it can handle it correctly, right? Is that being filled in properly?

**Comment by jmalak** [comment]
It could be fix by latest fixes related to Windows 9x see issue #852.
Please recheck with latest OW build.
