### ISSUE TITLE
Building project with Ninja Generator on Windows fails

### ISSUE THREAD

**Issue by madebr** [open-watcom/open-watcom-v2#936]
When building a CMake project, using the Ninja generator the build fails with the following error:
```
 Error: Unable to open temporary file "__wcl__.lnk" - Permission denied
```
[See the output of this CI workflow](https://github.com/madebr/SDL/runs/7587996497?check_suite_focus=true#step:10:205)

This error does not happen on my Linux dev system, only on Windows.
Switching to the `Watcom WMake` generator makes the error go away, but then I lose the parallelization time savings.

**Comment by jmalak** [comment]
Now existing temporary file is check and if file exists it is reported as error
if -fd option is used then file name specified by fd option is used for temporary file creation instead of default `__wcl__.lnk`
Before this change `__wcl__.lnk` file was always created and used and after linking it was renamed to file specified by -fd option

**Comment by jmalak** [comment]
Please check with latest release build.
Now for linker is generated unique temporary file from range `__wcl_00.lnk` up to `__wcl_99.lnk` by open( ...., O_CREAT | O_EXCL ...) as you suggested.

**Comment by madebr** [comment]
Works 💯!
Thanks for investing your time in this!

[Now CMake is blocking me from using the Ninja generator on Windows.](https://gitlab.kitware.com/cmake/cmake/-/issues/23806)
