### ISSUE TITLE
Unable to use dwindows

### ISSUE THREAD

**Issue by alter-ego-of-3oheicrw** [open-watcom/open-watcom-v2#976]
Download dwindows library here: https://dbsoft.org/dwindows/dwindows-win32-3.1.zip

The test we are trying to compile: https://github.com/dbsoft/dwindows/blob/master/dwtest.c

[dwtest.err.txt](https://github.com/open-watcom/open-watcom-v2/files/9858448/dwtest.err.txt)

**Comment by alter-ego-of-3oheicrw** [comment]
A closer look at the errors generated we found:

```
dw.h(984): Error! E1055: Unable to open 'gtk/gtk.h'
dw.h(988): Error! E1055: Unable to open 'gdk/gdk.h'
dw.h(990): Error! E1055: Unable to open 'gdk/gdkprivate.h'
dw.h(991): Error! E1055: Unable to open 'gdk/gdkkeysyms.h'
```

We are on Win32, why it's trying to use GTK? I used this small code to check if `__WIN32__` is defined or not. It turned out `__WIN32__` is not defined!

```
#include <stdio.h>

int main(void) {
    #if defined(__WIN32__)
        puts("foo\n");
    #endif
    return 0;
}

```

**Comment by alter-ego-of-3oheicrw** [comment]
I checked and found `_WIN32` is defined. To keep compatible with code expecting the MinGW compiler, should we add a macro to define `__WIN32__` by default too?

**Comment by alter-ego-of-3oheicrw** [comment]
I ended up patch `dw.h` to add `#define __WIN32__ _WIN32` and this is the new dwtest.err:

[dwtest.err.txt](https://github.com/open-watcom/open-watcom-v2/files/9858566/dwtest.err.txt)

**Comment by jmalak** [comment]
Sorry OW is not clone of MS or GCC or CLANG or MinGW compilers.
It is supposed that you will read minimum about compiler predefined macros instead of expecting that OW define same predefined macros as you expect.
OW is cross-compiler and handle multiple OS-es that predefined macros are different from other compilers.
Generally your code is not portable (is compiler centric) and expect many things which is not portable.
Anyway OW define `_WIN32` macro if specified target is 32-bit Windows by `-bt=nt` etc.
[OW predefined macros](https://open-watcom.github.io/open-watcom-v2-wikidocs/cguide.html#Open_Watcom_CDCPP_Predefined_Macros)

**Comment by alter-ego-of-3oheicrw** [comment]
> Sorry OW is not clone of MS or GCC or CLANG or MinGW compilers. It is supposed that you will read minimum about compiler predefined macros instead of expecting that OW define same predefined macros as you expect. OW is cross-compiler and handle multiple OS-es that predefined macros are different from other compilers. Generally your code is not portable (is compiler centric) and expect many things which is not portable. Anyway OW define `_WIN32` macro if specified target is 32-bit Windows by `-bt=nt` etc. [OW predefined macros](https://open-watcom.github.io/open-watcom-v2-wikidocs/cguide.html#Open_Watcom_CDCPP_Predefined_Macros)

It's not my code. I'm just trying to use it. After I used the hack `#define __WIN32__ _WIN32` it's still failed to compile with other errors. Please have a look at it.

**Comment by jmalak** [comment]
I recommend how you can fix it, because this code is non-portable.
I will not fix a problems in your code (even if you are not author) or incorrect use of OW tools by you.
If you get serious problem then describe it here and it can be resolved.
But add listing of lot of messages unrelated to problem (caused by incorrect use of OW tools) is useless work.

**Comment by alter-ego-of-3oheicrw** [comment]
`dwcompat.h` seems to be the source of many problems. Please stop telling this software is not portable. The author cared about portability a lot that he added `dwcompat.h`. If you have a look at that file, you will see `__WATCOMC__` is also covered. He tried his best, but his primary development platform is macOS. He can't test every C compilers available on the universe.

**Comment by alter-ego-of-3oheicrw** [comment]
This is `dwtest.err` after I commented out `dwcompat.h`:

[dwtest.err.txt](https://github.com/open-watcom/open-watcom-v2/files/9868403/dwtest.err.txt)

Please have a look at it. Thanks.

**Comment by alter-ego-of-3oheicrw** [comment]
Sorry everyone. I found the problem. I'm building the `dwtest.c` from the current branch of `dwindows` (not yet released) against an older version of the library (the stable release). It seems the current library changed too much compared to the stable release. I will close this ticket. Sorry again.
