### ISSUE TITLE
IDE message window messed-up

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#991]
I notice that the compile message window in the IDE has some strange bug. First, the scroll bar doesn't seem to work. Second, when scrolling text lines change. Third, when going up on the first row, stuff that is above will show on the first line.

I also notice that the GUI debugger source window initially only display one line. This can be fixed by using page up and page down. 

It's possible these bugs are related.

In previous versions, this worked fine, so must be some new bug in the GUI.

**Comment by pwroberts** [comment]
I see this bug too in recent-ish versions, and I also recall it working fine in previous versions (>>1 year ago). It's as if scrolling the compile message output window doesn't redraw the whole visible area, but rather only redraws 1 or 2 lines of text. I'm using the Win64 build on Windows 10.

**Comment by TS32423** [comment]
This bug is also annoying me. I just checked since when this bug is alive. The ide.exe from 2021-07-01 is the last one which is OK. I simply copied the ide.exe to my installation and everything is fine. I do not know what change happend from 2021-07 to 2021-08, but maybe this is a hint to the developer.

**Comment by jmalak** [comment]
This is problem in gui project which is common for IDE, WDW and WPROF projects. All these projects are affected.
I will try to fix it with higher priority.

**Comment by ArmstrongJ** [comment]
I just want to bump this bug. The IDE message log, when building, seems to scroll to the right-most extent when a string is added.  Because errors are quite often drastically shorter strings than a compiler string, errors can be missed since the message log has scrolled right.  The scrollbar's not working correctly makes this bug particularly frustrating because it is quite difficult to get the IDE's message log to scroll to the left-most text position.

I'm seeing this behavior on Windows 10, 11, 3.11, and WINE.  I've personally implemented a forced _setScrollTextPos( WScrollBarHorizontal, 0 );_ in _VListBox::insertString_ to counteract the "scroll right" behavior, but it isn't a fix as the scroll bars still don't work correctly.

**Comment by jmalak** [comment]
fixed by commit 12afe6e22d09473ac3ddb69abf699cbb1945c844
